// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allocations.sql

package sqlcgen

import (
	"context"
	"time"
)

const allocationsByFunction = `-- name: AllocationsByFunction :many
SELECT
  a.user_id,
  u.name AS seller_name,
  a.quantity AS assigned,
  (SELECT COALESCE(SUM(s.quantity), 0) FROM sales s
   WHERE s.seller_id = a.user_id AND s.function_id = a.function_id
     AND s.voided_at IS NULL AND NOT s.is_comp)::bigint AS sold
FROM allocations a
JOIN users u ON a.user_id = u.id
WHERE a.function_id = $1::bigint
ORDER BY u.name
`

type AllocationsByFunctionRow struct {
	UserID     int64  `json:"user_id"`
	SellerName string `json:"seller_name"`
	Assigned   int32  `json:"assigned"`
	Sold       int64  `json:"sold"`
}

// Asignaciones de una funcion con lo vendido por cada corista (cortesias y
// anuladas no cuentan).
func (q *Queries) AllocationsByFunction(ctx context.Context, functionID int64) ([]AllocationsByFunctionRow, error) {
	rows, err := q.db.Query(ctx, allocationsByFunction, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllocationsByFunctionRow{}
	for rows.Next() {
		var i AllocationsByFunctionRow
		if err := rows.Scan(
			&i.UserID,
			&i.SellerName,
			&i.Assigned,
			&i.Sold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllocation = `-- name: DeleteAllocation :exec
DELETE FROM allocations
WHERE user_id = $1::bigint AND function_id = $2::bigint
`

type DeleteAllocationParams struct {
	UserID     int64 `json:"user_id"`
	FunctionID int64 `json:"function_id"`
}

func (q *Queries) DeleteAllocation(ctx context.Context, arg DeleteAllocationParams) error {
	_, err := q.db.Exec(ctx, deleteAllocation, arg.UserID, arg.FunctionID)
	return err
}

const getPublicTicket = `-- name: GetPublicTicket :one
SELECT
  t.code,
  t.status,
  s.buyer_name,
  s.quantity AS sale_quantity,
  s.is_comp,
  s.voided_at,
  seller.name AS seller_name,
  f.name AS function_name,
  f.venue,
  f.starts_at,
  (SELECT count(*) FROM tickets t2 WHERE t2.sale_id = t.sale_id AND t2.id <= t.id)::bigint AS ticket_index
FROM tickets t
JOIN sales s ON t.sale_id = s.id
JOIN users seller ON s.seller_id = seller.id
JOIN functions f ON s.function_id = f.id
WHERE t.code = $1::text
`

type GetPublicTicketRow struct {
	Code         string     `json:"code"`
	Status       string     `json:"status"`
	BuyerName    string     `json:"buyer_name"`
	SaleQuantity int32      `json:"sale_quantity"`
	IsComp       bool       `json:"is_comp"`
	VoidedAt     *time.Time `json:"voided_at"`
	SellerName   string     `json:"seller_name"`
	FunctionName *string    `json:"function_name"`
	Venue        string     `json:"venue"`
	StartsAt     time.Time  `json:"starts_at"`
	TicketIndex  int64      `json:"ticket_index"`
}

// Todo lo que necesita la pagina publica de UNA entrada (/t/{code}).
func (q *Queries) GetPublicTicket(ctx context.Context, code string) (GetPublicTicketRow, error) {
	row := q.db.QueryRow(ctx, getPublicTicket, code)
	var i GetPublicTicketRow
	err := row.Scan(
		&i.Code,
		&i.Status,
		&i.BuyerName,
		&i.SaleQuantity,
		&i.IsComp,
		&i.VoidedAt,
		&i.SellerName,
		&i.FunctionName,
		&i.Venue,
		&i.StartsAt,
		&i.TicketIndex,
	)
	return i, err
}

const myAllocations = `-- name: MyAllocations :many
SELECT
  a.function_id,
  f.name AS function_name,
  f.venue,
  f.starts_at,
  a.quantity AS assigned,
  (SELECT COALESCE(SUM(s.quantity), 0) FROM sales s
   WHERE s.seller_id = a.user_id AND s.function_id = a.function_id
     AND s.voided_at IS NULL AND NOT s.is_comp)::bigint AS sold
FROM allocations a
JOIN functions f ON a.function_id = f.id
WHERE a.user_id = $1::bigint
ORDER BY f.starts_at
`

type MyAllocationsRow struct {
	FunctionID   int64     `json:"function_id"`
	FunctionName *string   `json:"function_name"`
	Venue        string    `json:"venue"`
	StartsAt     time.Time `json:"starts_at"`
	Assigned     int32     `json:"assigned"`
	Sold         int64     `json:"sold"`
}

// Las asignaciones de una corista, con la funcion y su avance de venta.
func (q *Queries) MyAllocations(ctx context.Context, userID int64) ([]MyAllocationsRow, error) {
	rows, err := q.db.Query(ctx, myAllocations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyAllocationsRow{}
	for rows.Next() {
		var i MyAllocationsRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionName,
			&i.Venue,
			&i.StartsAt,
			&i.Assigned,
			&i.Sold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAllocation = `-- name: UpsertAllocation :one
INSERT INTO allocations (user_id, function_id, quantity)
VALUES ($1::bigint, $2::bigint, $3::integer)
ON CONFLICT (user_id, function_id)
DO UPDATE SET quantity = EXCLUDED.quantity
RETURNING id, user_id, function_id, quantity, created_at
`

type UpsertAllocationParams struct {
	UserID     int64 `json:"user_id"`
	FunctionID int64 `json:"function_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) UpsertAllocation(ctx context.Context, arg UpsertAllocationParams) (Allocation, error) {
	row := q.db.QueryRow(ctx, upsertAllocation, arg.UserID, arg.FunctionID, arg.Quantity)
	var i Allocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FunctionID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
