// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allocations.sql

package sqlcgen

import (
	"context"
	"time"
)

const deleteAllocation = `-- name: DeleteAllocation :exec
DELETE FROM allocations
WHERE user_id = $1::bigint AND function_id = $2::bigint
`

type DeleteAllocationParams struct {
	UserID     int64 `json:"user_id"`
	FunctionID int64 `json:"function_id"`
}

func (q *Queries) DeleteAllocation(ctx context.Context, arg DeleteAllocationParams) error {
	_, err := q.db.Exec(ctx, deleteAllocation, arg.UserID, arg.FunctionID)
	return err
}

const deleteAllocationsForUser = `-- name: DeleteAllocationsForUser :exec
DELETE FROM allocations WHERE user_id = $1::bigint
`

// Al salir del rol de corista (o al desactivarse) se le sueltan los cupos:
// si no, quedan reservando lugares que nadie puede vender ni ver.
func (q *Queries) DeleteAllocationsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAllocationsForUser, userID)
	return err
}

const functionAllocationBoard = `-- name: FunctionAllocationBoard :many
SELECT
  u.id AS user_id,
  u.name AS seller_name,
  COALESCE(a.quantity, 0)::integer AS assigned,
  (SELECT COUNT(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.seller_id = u.id AND s.function_id = $1::bigint
     AND NOT s.is_comp AND t.status <> 'void')::bigint AS sold
FROM users u
JOIN functions f ON f.id = $1::bigint
JOIN season_members m ON m.user_id = u.id AND m.season_id = f.season_id
LEFT JOIN allocations a ON a.user_id = u.id AND a.function_id = $1::bigint
WHERE m.role = 'seller' AND m.left_at IS NULL
ORDER BY u.name
`

type FunctionAllocationBoardRow struct {
	UserID     int64  `json:"user_id"`
	SellerName string `json:"seller_name"`
	Assigned   int32  `json:"assigned"`
	Sold       int64  `json:"sold"`
}

// Tablero de asignacion (C8): todas las coristas activas con su cupo y lo
// vendido. "Vendido" = tickets vivos de sus ventas no-cortesia: anular
// devuelve el cupo automaticamente, sin contador desnormalizado.
func (q *Queries) FunctionAllocationBoard(ctx context.Context, functionID int64) ([]FunctionAllocationBoardRow, error) {
	rows, err := q.db.Query(ctx, functionAllocationBoard, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FunctionAllocationBoardRow{}
	for rows.Next() {
		var i FunctionAllocationBoardRow
		if err := rows.Scan(
			&i.UserID,
			&i.SellerName,
			&i.Assigned,
			&i.Sold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllocationQty = `-- name: GetAllocationQty :one
SELECT quantity FROM allocations
WHERE user_id = $1::bigint AND function_id = $2::bigint
`

type GetAllocationQtyParams struct {
	UserID     int64 `json:"user_id"`
	FunctionID int64 `json:"function_id"`
}

func (q *Queries) GetAllocationQty(ctx context.Context, arg GetAllocationQtyParams) (int32, error) {
	row := q.db.QueryRow(ctx, getAllocationQty, arg.UserID, arg.FunctionID)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getPublicTicket = `-- name: GetPublicTicket :one
SELECT
  t.code,
  t.status,
  s.buyer_name,
  s.quantity AS sale_quantity,
  s.is_comp,
  s.voided_at,
  seller.name AS seller_name,
  f.name AS function_name,
  f.venue,
  f.starts_at,
  (SELECT count(*) FROM tickets t2 WHERE t2.sale_id = t.sale_id AND t2.id <= t.id)::bigint AS ticket_index
FROM tickets t
JOIN sales s ON t.sale_id = s.id
JOIN users seller ON s.seller_id = seller.id
JOIN functions f ON s.function_id = f.id
WHERE t.code = $1::text
`

type GetPublicTicketRow struct {
	Code         string     `json:"code"`
	Status       string     `json:"status"`
	BuyerName    string     `json:"buyer_name"`
	SaleQuantity int32      `json:"sale_quantity"`
	IsComp       bool       `json:"is_comp"`
	VoidedAt     *time.Time `json:"voided_at"`
	SellerName   string     `json:"seller_name"`
	FunctionName *string    `json:"function_name"`
	Venue        string     `json:"venue"`
	StartsAt     time.Time  `json:"starts_at"`
	TicketIndex  int64      `json:"ticket_index"`
}

// Todo lo que necesita la pagina publica de UNA entrada (/t/{code}).
func (q *Queries) GetPublicTicket(ctx context.Context, code string) (GetPublicTicketRow, error) {
	row := q.db.QueryRow(ctx, getPublicTicket, code)
	var i GetPublicTicketRow
	err := row.Scan(
		&i.Code,
		&i.Status,
		&i.BuyerName,
		&i.SaleQuantity,
		&i.IsComp,
		&i.VoidedAt,
		&i.SellerName,
		&i.FunctionName,
		&i.Venue,
		&i.StartsAt,
		&i.TicketIndex,
	)
	return i, err
}

const myAllocations = `-- name: MyAllocations :many
SELECT
  a.function_id,
  f.name AS function_name,
  f.venue,
  f.starts_at,
  a.quantity AS assigned,
  (SELECT COUNT(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.seller_id = a.user_id AND s.function_id = a.function_id
     AND NOT s.is_comp AND t.status <> 'void')::bigint AS sold
FROM allocations a
JOIN functions f ON a.function_id = f.id
WHERE a.user_id = $1::bigint
ORDER BY f.starts_at
`

type MyAllocationsRow struct {
	FunctionID   int64     `json:"function_id"`
	FunctionName *string   `json:"function_name"`
	Venue        string    `json:"venue"`
	StartsAt     time.Time `json:"starts_at"`
	Assigned     int32     `json:"assigned"`
	Sold         int64     `json:"sold"`
}

// Cupo y avance de la corista logueada, por funcion (C8: /api/me/allocations).
func (q *Queries) MyAllocations(ctx context.Context, userID int64) ([]MyAllocationsRow, error) {
	rows, err := q.db.Query(ctx, myAllocations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyAllocationsRow{}
	for rows.Next() {
		var i MyAllocationsRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionName,
			&i.Venue,
			&i.StartsAt,
			&i.Assigned,
			&i.Sold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const soldBySellerInFunction = `-- name: SoldBySellerInFunction :one
SELECT COUNT(*) FROM tickets t
JOIN sales s ON t.sale_id = s.id
WHERE s.seller_id = $1::bigint
  AND s.function_id = $2::bigint
  AND NOT s.is_comp
  AND t.status <> 'void'
`

type SoldBySellerInFunctionParams struct {
	SellerID   int64 `json:"seller_id"`
	FunctionID int64 `json:"function_id"`
}

// Base del cupo consumido: tickets vivos de ventas no-cortesia.
func (q *Queries) SoldBySellerInFunction(ctx context.Context, arg SoldBySellerInFunctionParams) (int64, error) {
	row := q.db.QueryRow(ctx, soldBySellerInFunction, arg.SellerID, arg.FunctionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sumAllocations = `-- name: SumAllocations :one
SELECT COALESCE(SUM(a.quantity), 0)::bigint
FROM allocations a
JOIN functions f ON f.id = a.function_id
JOIN season_members m ON m.user_id = a.user_id AND m.season_id = f.season_id
WHERE a.function_id = $1::bigint
  AND m.role = 'seller' AND m.left_at IS NULL
`

// Cuenta lo mismo que muestra el tablero: solo cupos de coristas activas. Si
// a alguien le cambian el rol o la desactivan, su fila queda invisible en
// pantalla; contarla aca hacia que el total validado no coincidiera con el
// total en pantalla y que asignar el ultimo cupo fallara con numeros que no
// estaban en ningun lado.
func (q *Queries) SumAllocations(ctx context.Context, functionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, sumAllocations, functionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertAllocation = `-- name: UpsertAllocation :one
INSERT INTO allocations (user_id, function_id, quantity)
VALUES ($1::bigint, $2::bigint, $3::integer)
ON CONFLICT (user_id, function_id)
DO UPDATE SET quantity = EXCLUDED.quantity
RETURNING id, user_id, function_id, quantity, created_at
`

type UpsertAllocationParams struct {
	UserID     int64 `json:"user_id"`
	FunctionID int64 `json:"function_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) UpsertAllocation(ctx context.Context, arg UpsertAllocationParams) (Allocation, error) {
	row := q.db.QueryRow(ctx, upsertAllocation, arg.UserID, arg.FunctionID, arg.Quantity)
	var i Allocation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FunctionID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
