// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkins.sql

package sqlcgen

import (
	"context"
	"time"
)

const countCheckinsForFunction = `-- name: CountCheckinsForFunction :one
SELECT count(*)
FROM checkins c
JOIN tickets t ON c.ticket_id = t.id
JOIN sales s ON t.sale_id = s.id
WHERE s.function_id = $1
`

func (q *Queries) CountCheckinsForFunction(ctx context.Context, functionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckinsForFunction, functionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const doorSnapshotCheckins = `-- name: DoorSnapshotCheckins :many
SELECT
  t.code AS ticket_code,
  c.created_at,
  c.method,
  u.name AS by_name
FROM checkins c
JOIN tickets t ON c.ticket_id = t.id
JOIN sales s ON t.sale_id = s.id
JOIN users u ON c.user_id = u.id
WHERE s.function_id = $1
ORDER BY c.created_at
`

type DoorSnapshotCheckinsRow struct {
	TicketCode string    `json:"ticket_code"`
	CreatedAt  time.Time `json:"created_at"`
	Method     string    `json:"method"`
	ByName     string    `json:"by_name"`
}

func (q *Queries) DoorSnapshotCheckins(ctx context.Context, functionID int64) ([]DoorSnapshotCheckinsRow, error) {
	rows, err := q.db.Query(ctx, doorSnapshotCheckins, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoorSnapshotCheckinsRow{}
	for rows.Next() {
		var i DoorSnapshotCheckinsRow
		if err := rows.Scan(
			&i.TicketCode,
			&i.CreatedAt,
			&i.Method,
			&i.ByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const doorSnapshotTickets = `-- name: DoorSnapshotTickets :many
SELECT
  t.code,
  t.status,
  -- sale_id agrupa las entradas de una misma compra: la busqueda por nombre
  -- muestra una fila por comprador, no tres renglones identicos.
  s.id AS sale_id,
  s.buyer_name,
  u.name AS seller_name,
  s.is_comp
FROM tickets t
JOIN sales s ON t.sale_id = s.id
JOIN users u ON s.seller_id = u.id
WHERE s.function_id = $1
ORDER BY s.buyer_name, t.id
`

type DoorSnapshotTicketsRow struct {
	Code       string `json:"code"`
	Status     string `json:"status"`
	SaleID     int64  `json:"sale_id"`
	BuyerName  string `json:"buyer_name"`
	SellerName string `json:"seller_name"`
	IsComp     bool   `json:"is_comp"`
}

// Todo lo que la puerta necesita de cada ticket. Sin montos ni contacto:
// el rol door no ve plata (spec §3).
func (q *Queries) DoorSnapshotTickets(ctx context.Context, functionID int64) ([]DoorSnapshotTicketsRow, error) {
	rows, err := q.db.Query(ctx, doorSnapshotTickets, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoorSnapshotTicketsRow{}
	for rows.Next() {
		var i DoorSnapshotTicketsRow
		if err := rows.Scan(
			&i.Code,
			&i.Status,
			&i.SaleID,
			&i.BuyerName,
			&i.SellerName,
			&i.IsComp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckinByTicket = `-- name: GetCheckinByTicket :one
SELECT c.id, c.ticket_id, c.user_id, c.method, c.device_id, c.created_at, u.name AS by_name
FROM checkins c
JOIN users u ON c.user_id = u.id
WHERE c.ticket_id = $1
`

type GetCheckinByTicketRow struct {
	ID        int64     `json:"id"`
	TicketID  int64     `json:"ticket_id"`
	UserID    int64     `json:"user_id"`
	Method    string    `json:"method"`
	DeviceID  *string   `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
	ByName    string    `json:"by_name"`
}

func (q *Queries) GetCheckinByTicket(ctx context.Context, ticketID int64) (GetCheckinByTicketRow, error) {
	row := q.db.QueryRow(ctx, getCheckinByTicket, ticketID)
	var i GetCheckinByTicketRow
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.Method,
		&i.DeviceID,
		&i.CreatedAt,
		&i.ByName,
	)
	return i, err
}

const insertCheckin = `-- name: InsertCheckin :one
INSERT INTO checkins (ticket_id, user_id, method, device_id, created_at)
VALUES (
  $1::bigint,
  $2::bigint,
  $3::text,
  $4,
  $5::timestamptz
)
ON CONFLICT (ticket_id) DO NOTHING
RETURNING id, ticket_id, user_id, method, device_id, created_at
`

type InsertCheckinParams struct {
	TicketID  int64     `json:"ticket_id"`
	UserID    int64     `json:"user_id"`
	Method    string    `json:"method"`
	DeviceID  *string   `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

// ON CONFLICT DO NOTHING + UNIQUE(ticket_id): si el ticket ya entro, no
// devuelve fila (pgx.ErrNoRows) y el handler responde already_checked_in.
func (q *Queries) InsertCheckin(ctx context.Context, arg InsertCheckinParams) (Checkin, error) {
	row := q.db.QueryRow(ctx, insertCheckin,
		arg.TicketID,
		arg.UserID,
		arg.Method,
		arg.DeviceID,
		arg.CreatedAt,
	)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.Method,
		&i.DeviceID,
		&i.CreatedAt,
	)
	return i, err
}

const markTicketCheckedIn = `-- name: MarkTicketCheckedIn :exec
UPDATE tickets SET status = 'checked_in' WHERE id = $1 AND status = 'issued'
`

func (q *Queries) MarkTicketCheckedIn(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markTicketCheckedIn, id)
	return err
}
