// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: functions.sql

package sqlcgen

import (
	"context"
	"time"
)

const copySeasonFunctions = `-- name: CopySeasonFunctions :many
INSERT INTO functions (season_id, name, venue, starts_at, capacity, price_cents)
SELECT $1::bigint, f.name, f.venue,
       f.starts_at + interval '364 days', f.capacity, f.price_cents
FROM functions f
WHERE f.season_id = $2::bigint
ORDER BY f.starts_at
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type CopySeasonFunctionsParams struct {
	ToSeasonID   int64 `json:"to_season_id"`
	FromSeasonID int64 `json:"from_season_id"`
}

// Duplica la grilla de una temporada en otra: mismo lugar, cupo y precio, con
// las fechas corridas 364 dias (52 semanas exactas) para que cada funcion caiga
// el mismo dia de la semana del año siguiente. Las fechas se ajustan despues;
// lo que se ahorra es cargar la estructura entera a mano.
func (q *Queries) CopySeasonFunctions(ctx context.Context, arg CopySeasonFunctionsParams) ([]Function, error) {
	rows, err := q.db.Query(ctx, copySeasonFunctions, arg.ToSeasonID, arg.FromSeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Function{}
	for rows.Next() {
		var i Function
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.PriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSalesForFunction = `-- name: CountSalesForFunction :one
SELECT count(*)::bigint FROM sales WHERE function_id = $1
`

// Cualquier venta, incluso anulada: si alguna vez se vendio algo, la funcion
// ya no se puede borrar y hay que hablar de reembolsos, no de un boton.
func (q *Queries) CountSalesForFunction(ctx context.Context, functionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesForFunction, functionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFunction = `-- name: CreateFunction :one
INSERT INTO functions (season_id, name, venue, starts_at, capacity, price_cents)
VALUES (
  $1::bigint,
  $2,
  $3::text,
  $4::timestamptz,
  $5::integer,
  $6::bigint
)
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type CreateFunctionParams struct {
	SeasonID   int64     `json:"season_id"`
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	PriceCents int64     `json:"price_cents"`
}

func (q *Queries) CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, createFunction,
		arg.SeasonID,
		arg.Name,
		arg.Venue,
		arg.StartsAt,
		arg.Capacity,
		arg.PriceCents,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllocationsForFunction = `-- name: DeleteAllocationsForFunction :exec
DELETE FROM allocations WHERE function_id = $1
`

func (q *Queries) DeleteAllocationsForFunction(ctx context.Context, functionID int64) error {
	_, err := q.db.Exec(ctx, deleteAllocationsForFunction, functionID)
	return err
}

const deleteFunction = `-- name: DeleteFunction :exec
DELETE FROM functions WHERE id = $1
`

func (q *Queries) DeleteFunction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFunction, id)
	return err
}

const getFunction = `-- name: GetFunction :one
SELECT id, season_id, name, venue, starts_at, capacity, price_cents, created_at FROM functions WHERE id = $1
`

func (q *Queries) GetFunction(ctx context.Context, id int64) (Function, error) {
	row := q.db.QueryRow(ctx, getFunction, id)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const listFunctions = `-- name: ListFunctions :many
SELECT
  f.id, f.season_id, f.name, f.venue, f.starts_at, f.capacity, f.price_cents, f.created_at,
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND t.status <> 'void')::bigint AS sold,
  (SELECT count(*) FROM checkins c
   JOIN tickets t ON c.ticket_id = t.id
   JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id)::bigint AS entered,
  -- Cupo repartido entre coristas activas: lo mismo que cuenta el tablero.
  (SELECT COALESCE(SUM(a.quantity), 0) FROM allocations a
   JOIN users au ON au.id = a.user_id
   WHERE a.function_id = f.id AND au.role = 'seller' AND au.is_active)::bigint AS assigned,
  -- Cortesias emitidas. Es un conteo, no plata: en la puerta importa saber
  -- cuantos de los que vienen no pagaron entrada.
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND s.is_comp AND t.status <> 'void')::bigint AS comp_tickets,
  -- Cuantas coristas vendieron algo para esta funcion. Tambien un conteo.
  (SELECT count(DISTINCT s.seller_id) FROM sales s
   WHERE s.function_id = f.id AND s.voided_at IS NULL)::bigint AS sellers
FROM functions f
WHERE $1::bigint IS NULL OR f.season_id = $1::bigint
ORDER BY f.starts_at
`

type ListFunctionsRow struct {
	ID          int64     `json:"id"`
	SeasonID    int64     `json:"season_id"`
	Name        *string   `json:"name"`
	Venue       string    `json:"venue"`
	StartsAt    time.Time `json:"starts_at"`
	Capacity    int32     `json:"capacity"`
	PriceCents  int64     `json:"price_cents"`
	CreatedAt   time.Time `json:"created_at"`
	Sold        int64     `json:"sold"`
	Entered     int64     `json:"entered"`
	Assigned    int64     `json:"assigned"`
	CompTickets int64     `json:"comp_tickets"`
	Sellers     int64     `json:"sellers"`
}

// Incluye cuantas entradas vivas tiene cada funcion (para barras de progreso
// de venta) y cuantos ingresos ya se registraron: con ingresos, la funcion
// queda congelada (no se edita, spec §5.1) y la pantalla tiene que saberlo
// antes de ofrecer el formulario. Solo cuenta, no expone plata.
func (q *Queries) ListFunctions(ctx context.Context, seasonID *int64) ([]ListFunctionsRow, error) {
	rows, err := q.db.Query(ctx, listFunctions, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFunctionsRow{}
	for rows.Next() {
		var i ListFunctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.PriceCents,
			&i.CreatedAt,
			&i.Sold,
			&i.Entered,
			&i.Assigned,
			&i.CompTickets,
			&i.Sellers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFunction = `-- name: UpdateFunction :one
UPDATE functions
SET name        = $1,
    venue       = $2::text,
    starts_at   = $3::timestamptz,
    capacity    = $4::integer,
    price_cents = $5::bigint
WHERE id = $6::bigint
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type UpdateFunctionParams struct {
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	PriceCents int64     `json:"price_cents"`
	ID         int64     `json:"id"`
}

func (q *Queries) UpdateFunction(ctx context.Context, arg UpdateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, updateFunction,
		arg.Name,
		arg.Venue,
		arg.StartsAt,
		arg.Capacity,
		arg.PriceCents,
		arg.ID,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}
