// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: functions.sql

package sqlcgen

import (
	"context"
	"time"
)

const copySeasonFunctions = `-- name: CopySeasonFunctions :many
INSERT INTO functions (season_id, name, venue, starts_at, capacity, price_cents)
SELECT a.id, f.name, f.venue,
       f.starts_at + interval '364 days', f.capacity, f.price_cents
FROM functions f
JOIN seasons de ON de.id = f.season_id
JOIN seasons a  ON a.id = $1::bigint
WHERE f.season_id = $2::bigint
  AND de.organization_id = $3::bigint
  AND a.organization_id  = $3::bigint
ORDER BY f.starts_at
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type CopySeasonFunctionsParams struct {
	ToSeasonID     int64 `json:"to_season_id"`
	FromSeasonID   int64 `json:"from_season_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Duplica la grilla de una temporada en otra: mismo lugar, cupo y precio, con
// las fechas corridas 364 dias (52 semanas exactas) para que cada funcion caiga
// el mismo dia de la semana del año siguiente. Las fechas se ajustan despues;
// lo que se ahorra es cargar la estructura entera a mano.
// Las dos temporadas tienen que ser de la organizacion.
func (q *Queries) CopySeasonFunctions(ctx context.Context, arg CopySeasonFunctionsParams) ([]Function, error) {
	rows, err := q.db.Query(ctx, copySeasonFunctions, arg.ToSeasonID, arg.FromSeasonID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Function{}
	for rows.Next() {
		var i Function
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.PriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSalesForFunction = `-- name: CountSalesForFunction :one
SELECT count(*)::bigint FROM sales sa
JOIN functions f ON f.id = sa.function_id
JOIN seasons se ON se.id = f.season_id
WHERE sa.function_id = $1::bigint
  AND se.organization_id = $2::bigint
`

type CountSalesForFunctionParams struct {
	FunctionID     int64 `json:"function_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Cualquier venta, incluso anulada: si alguna vez se vendio algo, la funcion
// ya no se puede borrar y hay que hablar de reembolsos, no de un boton.
func (q *Queries) CountSalesForFunction(ctx context.Context, arg CountSalesForFunctionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesForFunction, arg.FunctionID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createFunction = `-- name: CreateFunction :one

INSERT INTO functions (season_id, name, venue, starts_at, capacity, price_cents)
SELECT s.id,
  $1,
  $2::text,
  $3::timestamptz,
  $4::integer,
  $5::bigint
FROM seasons s
WHERE s.id = $6::bigint
  AND s.organization_id = $7::bigint
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type CreateFunctionParams struct {
	Name           *string   `json:"name"`
	Venue          string    `json:"venue"`
	StartsAt       time.Time `json:"starts_at"`
	Capacity       int32     `json:"capacity"`
	PriceCents     int64     `json:"price_cents"`
	SeasonID       int64     `json:"season_id"`
	OrganizationID int64     `json:"organization_id"`
}

// functions no tiene organization_id: cuelga de seasons (C17 §A.1). Toda
// consulta llega a la organizacion por la temporada; una funcion de otra
// organizacion no existe (ErrNoRows → 404).
// Solo si la temporada es de la organizacion; si no, no inserta y devuelve
// ErrNoRows.
func (q *Queries) CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, createFunction,
		arg.Name,
		arg.Venue,
		arg.StartsAt,
		arg.Capacity,
		arg.PriceCents,
		arg.SeasonID,
		arg.OrganizationID,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllocationsForFunction = `-- name: DeleteAllocationsForFunction :exec
DELETE FROM allocations a
USING functions f, seasons se
WHERE f.id = a.function_id AND se.id = f.season_id
  AND a.function_id = $1::bigint
  AND se.organization_id = $2::bigint
`

type DeleteAllocationsForFunctionParams struct {
	FunctionID     int64 `json:"function_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) DeleteAllocationsForFunction(ctx context.Context, arg DeleteAllocationsForFunctionParams) error {
	_, err := q.db.Exec(ctx, deleteAllocationsForFunction, arg.FunctionID, arg.OrganizationID)
	return err
}

const deleteFunction = `-- name: DeleteFunction :exec
DELETE FROM functions f
USING seasons se
WHERE se.id = f.season_id
  AND f.id = $1::bigint
  AND se.organization_id = $2::bigint
`

type DeleteFunctionParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) DeleteFunction(ctx context.Context, arg DeleteFunctionParams) error {
	_, err := q.db.Exec(ctx, deleteFunction, arg.ID, arg.OrganizationID)
	return err
}

const getFunction = `-- name: GetFunction :one
SELECT f.id, f.season_id, f.name, f.venue, f.starts_at, f.capacity, f.price_cents, f.created_at FROM functions f
JOIN seasons se ON se.id = f.season_id
WHERE f.id = $1::bigint
  AND se.organization_id = $2::bigint
`

type GetFunctionParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetFunction(ctx context.Context, arg GetFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, getFunction, arg.ID, arg.OrganizationID)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const listFunctions = `-- name: ListFunctions :many
SELECT
  f.id, f.season_id, f.name, f.venue, f.starts_at, f.capacity, f.price_cents, f.created_at,
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND t.status <> 'void')::bigint AS sold,
  (SELECT count(*) FROM checkins c
   JOIN tickets t ON c.ticket_id = t.id
   JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id)::bigint AS entered,
  -- Cupo repartido entre coristas que siguen en la temporada de esta funcion.
  (SELECT COALESCE(SUM(a.quantity), 0) FROM allocations a
   JOIN season_members m ON m.user_id = a.user_id AND m.season_id = f.season_id
   WHERE a.function_id = f.id AND m.role = 'seller' AND m.left_at IS NULL)::bigint AS assigned,
  -- Cortesias emitidas. Es un conteo, no plata: en la puerta importa saber
  -- cuantos de los que vienen no pagaron entrada.
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND s.is_comp AND t.status <> 'void')::bigint AS comp_tickets,
  -- Cuantas coristas vendieron algo para esta funcion. Tambien un conteo.
  (SELECT count(DISTINCT s.seller_id) FROM sales s
   WHERE s.function_id = f.id AND s.voided_at IS NULL)::bigint AS sellers
FROM functions f
JOIN seasons se ON se.id = f.season_id
WHERE se.organization_id = $1::bigint
  AND ($2::bigint IS NULL OR f.season_id = $2::bigint)
ORDER BY f.starts_at
`

type ListFunctionsParams struct {
	OrganizationID int64  `json:"organization_id"`
	SeasonID       *int64 `json:"season_id"`
}

type ListFunctionsRow struct {
	ID          int64     `json:"id"`
	SeasonID    int64     `json:"season_id"`
	Name        *string   `json:"name"`
	Venue       string    `json:"venue"`
	StartsAt    time.Time `json:"starts_at"`
	Capacity    int32     `json:"capacity"`
	PriceCents  int64     `json:"price_cents"`
	CreatedAt   time.Time `json:"created_at"`
	Sold        int64     `json:"sold"`
	Entered     int64     `json:"entered"`
	Assigned    int64     `json:"assigned"`
	CompTickets int64     `json:"comp_tickets"`
	Sellers     int64     `json:"sellers"`
}

// Incluye cuantas entradas vivas tiene cada funcion (para barras de progreso
// de venta) y cuantos ingresos ya se registraron: con ingresos, la funcion
// queda congelada (no se edita, spec §5.1) y la pantalla tiene que saberlo
// antes de ofrecer el formulario. Solo cuenta, no expone plata.
func (q *Queries) ListFunctions(ctx context.Context, arg ListFunctionsParams) ([]ListFunctionsRow, error) {
	rows, err := q.db.Query(ctx, listFunctions, arg.OrganizationID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFunctionsRow{}
	for rows.Next() {
		var i ListFunctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.PriceCents,
			&i.CreatedAt,
			&i.Sold,
			&i.Entered,
			&i.Assigned,
			&i.CompTickets,
			&i.Sellers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFunction = `-- name: UpdateFunction :one
UPDATE functions f
SET name        = $1,
    venue       = $2::text,
    starts_at   = $3::timestamptz,
    capacity    = $4::integer,
    price_cents = $5::bigint
FROM seasons se
WHERE se.id = f.season_id
  AND f.id = $6::bigint
  AND se.organization_id = $7::bigint
RETURNING f.id, f.season_id, f.name, f.venue, f.starts_at, f.capacity, f.price_cents, f.created_at
`

type UpdateFunctionParams struct {
	Name           *string   `json:"name"`
	Venue          string    `json:"venue"`
	StartsAt       time.Time `json:"starts_at"`
	Capacity       int32     `json:"capacity"`
	PriceCents     int64     `json:"price_cents"`
	ID             int64     `json:"id"`
	OrganizationID int64     `json:"organization_id"`
}

func (q *Queries) UpdateFunction(ctx context.Context, arg UpdateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, updateFunction,
		arg.Name,
		arg.Venue,
		arg.StartsAt,
		arg.Capacity,
		arg.PriceCents,
		arg.ID,
		arg.OrganizationID,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}
