// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: functions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createFunction = `-- name: CreateFunction :one
INSERT INTO functions (season_id, name, venue, starts_at, capacity, price_cents)
VALUES (
  $1::bigint,
  $2,
  $3::text,
  $4::timestamptz,
  $5::integer,
  $6::bigint
)
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type CreateFunctionParams struct {
	SeasonID   int64     `json:"season_id"`
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	PriceCents int64     `json:"price_cents"`
}

func (q *Queries) CreateFunction(ctx context.Context, arg CreateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, createFunction,
		arg.SeasonID,
		arg.Name,
		arg.Venue,
		arg.StartsAt,
		arg.Capacity,
		arg.PriceCents,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getFunction = `-- name: GetFunction :one
SELECT id, season_id, name, venue, starts_at, capacity, price_cents, created_at FROM functions WHERE id = $1
`

func (q *Queries) GetFunction(ctx context.Context, id int64) (Function, error) {
	row := q.db.QueryRow(ctx, getFunction, id)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const listFunctions = `-- name: ListFunctions :many
SELECT
  f.id, f.season_id, f.name, f.venue, f.starts_at, f.capacity, f.price_cents, f.created_at,
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND t.status <> 'void')::bigint AS sold,
  (SELECT count(*) FROM checkins c
   JOIN tickets t ON c.ticket_id = t.id
   JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id)::bigint AS entered
FROM functions f
WHERE $1::bigint IS NULL OR f.season_id = $1::bigint
ORDER BY f.starts_at
`

type ListFunctionsRow struct {
	ID         int64     `json:"id"`
	SeasonID   int64     `json:"season_id"`
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	PriceCents int64     `json:"price_cents"`
	CreatedAt  time.Time `json:"created_at"`
	Sold       int64     `json:"sold"`
	Entered    int64     `json:"entered"`
}

// Incluye cuantas entradas vivas tiene cada funcion (para barras de progreso
// de venta) y cuantos ingresos ya se registraron: con ingresos, la funcion
// queda congelada (no se edita, spec §5.1) y la pantalla tiene que saberlo
// antes de ofrecer el formulario. Solo cuenta, no expone plata.
func (q *Queries) ListFunctions(ctx context.Context, seasonID *int64) ([]ListFunctionsRow, error) {
	rows, err := q.db.Query(ctx, listFunctions, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFunctionsRow{}
	for rows.Next() {
		var i ListFunctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.PriceCents,
			&i.CreatedAt,
			&i.Sold,
			&i.Entered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFunction = `-- name: UpdateFunction :one
UPDATE functions
SET name        = $1,
    venue       = $2::text,
    starts_at   = $3::timestamptz,
    capacity    = $4::integer,
    price_cents = $5::bigint
WHERE id = $6::bigint
RETURNING id, season_id, name, venue, starts_at, capacity, price_cents, created_at
`

type UpdateFunctionParams struct {
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	PriceCents int64     `json:"price_cents"`
	ID         int64     `json:"id"`
}

func (q *Queries) UpdateFunction(ctx context.Context, arg UpdateFunctionParams) (Function, error) {
	row := q.db.QueryRow(ctx, updateFunction,
		arg.Name,
		arg.Venue,
		arg.StartsAt,
		arg.Capacity,
		arg.PriceCents,
		arg.ID,
	)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}
