// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Checkin struct {
	ID        int64     `json:"id"`
	TicketID  int64     `json:"ticket_id"`
	UserID    int64     `json:"user_id"`
	Method    string    `json:"method"`
	DeviceID  *string   `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

type EmailSend struct {
	ID        int64     `json:"id"`
	SaleID    int64     `json:"sale_id"`
	Recipient string    `json:"recipient"`
	Status    string    `json:"status"`
	Error     *string   `json:"error"`
	CreatedAt time.Time `json:"created_at"`
}

type Function struct {
	ID         int64     `json:"id"`
	SeasonID   int64     `json:"season_id"`
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	PriceCents int64     `json:"price_cents"`
	CreatedAt  time.Time `json:"created_at"`
}

type Sale struct {
	ID            int64      `json:"id"`
	FunctionID    int64      `json:"function_id"`
	SellerID      int64      `json:"seller_id"`
	Code          string     `json:"code"`
	BuyerName     string     `json:"buyer_name"`
	BuyerEmail    *string    `json:"buyer_email"`
	BuyerPhone    *string    `json:"buyer_phone"`
	Quantity      int32      `json:"quantity"`
	AmountCents   int64      `json:"amount_cents"`
	PaymentStatus string     `json:"payment_status"`
	PaymentMethod *string    `json:"payment_method"`
	IsComp        bool       `json:"is_comp"`
	Notes         *string    `json:"notes"`
	VoidedAt      *time.Time `json:"voided_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type Season struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type Settlement struct {
	ID          int64     `json:"id"`
	SellerID    int64     `json:"seller_id"`
	SeasonID    int64     `json:"season_id"`
	AmountCents int64     `json:"amount_cents"`
	Method      string    `json:"method"`
	Notes       *string   `json:"notes"`
	CreatedAt   time.Time `json:"created_at"`
}

type Ticket struct {
	ID        int64     `json:"id"`
	SaleID    int64     `json:"sale_id"`
	Code      string    `json:"code"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Email              string    `json:"email"`
	PasswordHash       string    `json:"password_hash"`
	Role               string    `json:"role"`
	MustChangePassword bool      `json:"must_change_password"`
	CreatedAt          time.Time `json:"created_at"`
}
