// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"
)

const attendanceBySale = `-- name: AttendanceBySale :many
SELECT
  s.id AS sale_id,
  s.buyer_name,
  seller.name AS seller_name,
  s.is_comp,
  t.id AS ticket_id,
  c.created_at AS checkin_at,
  c.method AS checkin_method,
  checker.name AS checkin_by
FROM sales s
JOIN users seller ON s.seller_id = seller.id
JOIN tickets t ON t.sale_id = s.id
LEFT JOIN checkins c ON c.ticket_id = t.id
LEFT JOIN users checker ON c.user_id = checker.id
WHERE s.function_id = $1::bigint
  AND s.voided_at IS NULL
  AND t.status <> 'void'
ORDER BY s.id, t.id
`

type AttendanceBySaleRow struct {
	SaleID        int64      `json:"sale_id"`
	BuyerName     string     `json:"buyer_name"`
	SellerName    string     `json:"seller_name"`
	IsComp        bool       `json:"is_comp"`
	TicketID      int64      `json:"ticket_id"`
	CheckinAt     *time.Time `json:"checkin_at"`
	CheckinMethod *string    `json:"checkin_method"`
	CheckinBy     *string    `json:"checkin_by"`
}

// Asistencia por comprador (C6): una fila por entrada viva de la funcion con
// su check-in (o NULL si todavia no entro). El handler agrupa por venta.
func (q *Queries) AttendanceBySale(ctx context.Context, functionID int64) ([]AttendanceBySaleRow, error) {
	rows, err := q.db.Query(ctx, attendanceBySale, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceBySaleRow{}
	for rows.Next() {
		var i AttendanceBySaleRow
		if err := rows.Scan(
			&i.SaleID,
			&i.BuyerName,
			&i.SellerName,
			&i.IsComp,
			&i.TicketID,
			&i.CheckinAt,
			&i.CheckinMethod,
			&i.CheckinBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attentionPendingInvites = `-- name: AttentionPendingInvites :many
SELECT id AS user_id, name, role, created_at
FROM users
WHERE is_active AND last_login_at IS NULL
ORDER BY created_at
`

type AttentionPendingInvitesRow struct {
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// Gente del equipo que nunca entro a la app (C7 + C9).
func (q *Queries) AttentionPendingInvites(ctx context.Context) ([]AttentionPendingInvitesRow, error) {
	rows, err := q.db.Query(ctx, attentionPendingInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttentionPendingInvitesRow{}
	for rows.Next() {
		var i AttentionPendingInvitesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attentionSettlements = `-- name: AttentionSettlements :many
WITH collected AS (
  SELECT s.seller_id,
         COALESCE(SUM(s.paid_cents), 0)::bigint AS paid_cents,
         COALESCE(
           MAX((SELECT MAX(p.created_at) FROM sale_payments p WHERE p.sale_id = s.id)),
           '0001-01-01'::timestamptz) AS last_paid_at
  FROM sales s
  JOIN functions f ON s.function_id = f.id
  WHERE f.season_id = $1::bigint
    AND NOT s.is_comp
    AND s.voided_at IS NULL
  GROUP BY s.seller_id
), settled AS (
  SELECT seller_id, COALESCE(SUM(amount_cents), 0)::bigint AS cents
  FROM settlements
  WHERE season_id = $1::bigint
  GROUP BY seller_id
)
SELECT
  u.id AS seller_id,
  u.name AS seller_name,
  (c.paid_cents - COALESCE(st.cents, 0))::bigint AS balance_cents,
  -- Cobrado y rendido viajan con la alerta para que el pop-up de la home
  -- pueda armar su encabezado sin pedir el reporte entero (C14).
  c.paid_cents::bigint AS collected_cents,
  COALESCE(st.cents, 0)::bigint AS settled_cents,
  c.last_paid_at::timestamptz AS last_paid_at
FROM collected c
JOIN users u ON u.id = c.seller_id
LEFT JOIN settled st ON st.seller_id = c.seller_id
WHERE c.paid_cents - COALESCE(st.cents, 0) > 0
ORDER BY (c.paid_cents - COALESCE(st.cents, 0)) DESC
`

type AttentionSettlementsRow struct {
	SellerID       int64     `json:"seller_id"`
	SellerName     string    `json:"seller_name"`
	BalanceCents   int64     `json:"balance_cents"`
	CollectedCents int64     `json:"collected_cents"`
	SettledCents   int64     `json:"settled_cents"`
	LastPaidAt     time.Time `json:"last_paid_at"`
}

// Coristas con saldo a rendir (C9). `last_paid_at` es la fecha del cobro mas
// reciente, que desde que existen los cobros parciales se guarda de verdad.
// Centinela año 1 = todavia no cobro nada.
func (q *Queries) AttentionSettlements(ctx context.Context, seasonID int64) ([]AttentionSettlementsRow, error) {
	rows, err := q.db.Query(ctx, attentionSettlements, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttentionSettlementsRow{}
	for rows.Next() {
		var i AttentionSettlementsRow
		if err := rows.Scan(
			&i.SellerID,
			&i.SellerName,
			&i.BalanceCents,
			&i.CollectedCents,
			&i.SettledCents,
			&i.LastPaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attentionUnassigned = `-- name: AttentionUnassigned :many
SELECT
  f.id AS function_id,
  f.name,
  f.venue,
  f.starts_at,
  f.capacity,
  COALESCE(SUM(a.quantity) FILTER (WHERE au.id IS NOT NULL), 0)::bigint AS assigned
FROM functions f
LEFT JOIN allocations a ON a.function_id = f.id
LEFT JOIN users au ON au.id = a.user_id AND au.role = 'seller' AND au.is_active
WHERE f.season_id = $1::bigint
  AND f.starts_at > now()
GROUP BY f.id
HAVING f.capacity > COALESCE(SUM(a.quantity) FILTER (WHERE au.id IS NOT NULL), 0)
ORDER BY f.starts_at
`

type AttentionUnassignedRow struct {
	FunctionID int64     `json:"function_id"`
	Name       *string   `json:"name"`
	Venue      string    `json:"venue"`
	StartsAt   time.Time `json:"starts_at"`
	Capacity   int32     `json:"capacity"`
	Assigned   int64     `json:"assigned"`
}

// Funciones que todavia no pasaron con entradas sin repartir entre coristas.
func (q *Queries) AttentionUnassigned(ctx context.Context, seasonID int64) ([]AttentionUnassignedRow, error) {
	rows, err := q.db.Query(ctx, attentionUnassigned, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttentionUnassignedRow{}
	for rows.Next() {
		var i AttentionUnassignedRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.Assigned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingSales = `-- name: CountPendingSales :one
SELECT count(*) FROM sales s
WHERE s.voided_at IS NULL
  AND NOT s.is_comp
  AND s.amount_cents > s.paid_cents
  AND ($1::bigint IS NULL OR s.seller_id = $1::bigint)
`

// Badge de "Vender": ventas con saldo. Global para direccion, propias para la
// corista.
func (q *Queries) CountPendingSales(ctx context.Context, sellerID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSales, sellerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO settlement_reminders (seller_id, season_id, sent_by, amount_cents, status)
VALUES ($1::bigint, $2::bigint,
        $3::bigint, $4::bigint, $5::text)
RETURNING id, seller_id, season_id, sent_by, amount_cents, status, created_at
`

type CreateReminderParams struct {
	SellerID    int64  `json:"seller_id"`
	SeasonID    int64  `json:"season_id"`
	SentBy      int64  `json:"sent_by"`
	AmountCents int64  `json:"amount_cents"`
	Status      string `json:"status"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (SettlementReminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.SellerID,
		arg.SeasonID,
		arg.SentBy,
		arg.AmountCents,
		arg.Status,
	)
	var i SettlementReminder
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.SeasonID,
		&i.SentBy,
		&i.AmountCents,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (seller_id, season_id, amount_cents, method, notes)
VALUES (
  $1::bigint,
  $2::bigint,
  $3::bigint,
  $4::text,
  $5
)
RETURNING id, seller_id, season_id, amount_cents, method, notes, created_at
`

type CreateSettlementParams struct {
	SellerID    int64   `json:"seller_id"`
	SeasonID    int64   `json:"season_id"`
	AmountCents int64   `json:"amount_cents"`
	Method      string  `json:"method"`
	Notes       *string `json:"notes"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.SellerID,
		arg.SeasonID,
		arg.AmountCents,
		arg.Method,
		arg.Notes,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.SeasonID,
		&i.AmountCents,
		&i.Method,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const functionsSummary = `-- name: FunctionsSummary :many
SELECT
  f.id,
  f.name,
  f.venue,
  f.starts_at,
  f.capacity,
  f.price_cents,
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND t.status <> 'void')::bigint AS sold,
  (SELECT COALESCE(SUM(s.paid_cents), 0) FROM sales s
   WHERE s.function_id = f.id AND NOT s.is_comp AND s.voided_at IS NULL)::bigint AS collected_cents,
  (SELECT COALESCE(SUM(a.quantity), 0) FROM allocations a
   JOIN users au ON au.id = a.user_id
   WHERE a.function_id = f.id AND au.role = 'seller' AND au.is_active)::bigint AS assigned,
  -- Cortesias emitidas: no son plata, pero ocupan butaca.
  (SELECT count(*) FROM tickets t JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id AND s.is_comp AND t.status <> 'void')::bigint AS comp_tickets,
  (SELECT count(*) FROM checkins c
   JOIN tickets t ON c.ticket_id = t.id
   JOIN sales s ON t.sale_id = s.id
   WHERE s.function_id = f.id)::bigint AS entered
FROM functions f
WHERE f.season_id = $1::bigint
ORDER BY f.starts_at
`

type FunctionsSummaryRow struct {
	ID             int64     `json:"id"`
	Name           *string   `json:"name"`
	Venue          string    `json:"venue"`
	StartsAt       time.Time `json:"starts_at"`
	Capacity       int32     `json:"capacity"`
	PriceCents     int64     `json:"price_cents"`
	Sold           int64     `json:"sold"`
	CollectedCents int64     `json:"collected_cents"`
	Assigned       int64     `json:"assigned"`
	CompTickets    int64     `json:"comp_tickets"`
	Entered        int64     `json:"entered"`
}

// El pulso de la temporada funcion por funcion (C9): vendidas sobre cupo,
// recaudado, asignado y cuantos ingresaron. Todo derivado, sin contadores.
func (q *Queries) FunctionsSummary(ctx context.Context, seasonID int64) ([]FunctionsSummaryRow, error) {
	rows, err := q.db.Query(ctx, functionsSummary, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FunctionsSummaryRow{}
	for rows.Next() {
		var i FunctionsSummaryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Venue,
			&i.StartsAt,
			&i.Capacity,
			&i.PriceCents,
			&i.Sold,
			&i.CollectedCents,
			&i.Assigned,
			&i.CompTickets,
			&i.Entered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastReminders = `-- name: LastReminders :many
SELECT DISTINCT ON (seller_id) seller_id, created_at, status
FROM settlement_reminders
WHERE season_id = $1::bigint
ORDER BY seller_id, created_at DESC
`

type LastRemindersRow struct {
	SellerID  int64     `json:"seller_id"`
	CreatedAt time.Time `json:"created_at"`
	Status    string    `json:"status"`
}

// El ultimo recordatorio de cada corista de la temporada, para el ranking.
func (q *Queries) LastReminders(ctx context.Context, seasonID int64) ([]LastRemindersRow, error) {
	rows, err := q.db.Query(ctx, lastReminders, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastRemindersRow{}
	for rows.Next() {
		var i LastRemindersRow
		if err := rows.Scan(&i.SellerID, &i.CreatedAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminders = `-- name: ListReminders :many
SELECT id, seller_id, season_id, sent_by, amount_cents, status, created_at FROM settlement_reminders
WHERE seller_id = $1::bigint AND season_id = $2::bigint
ORDER BY created_at DESC
`

type ListRemindersParams struct {
	SellerID int64 `json:"seller_id"`
	SeasonID int64 `json:"season_id"`
}

func (q *Queries) ListReminders(ctx context.Context, arg ListRemindersParams) ([]SettlementReminder, error) {
	rows, err := q.db.Query(ctx, listReminders, arg.SellerID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementReminder{}
	for rows.Next() {
		var i SettlementReminder
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SeasonID,
			&i.SentBy,
			&i.AmountCents,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlements = `-- name: ListSettlements :many
SELECT st.id, st.seller_id, st.season_id, st.amount_cents, st.method, st.notes, st.created_at, u.name AS seller_name
FROM settlements st
JOIN users u ON st.seller_id = u.id
WHERE st.season_id = $1::bigint
  AND ($2::bigint IS NULL OR st.seller_id = $2::bigint)
ORDER BY st.created_at DESC
`

type ListSettlementsParams struct {
	SeasonID int64  `json:"season_id"`
	SellerID *int64 `json:"seller_id"`
}

type ListSettlementsRow struct {
	ID          int64     `json:"id"`
	SellerID    int64     `json:"seller_id"`
	SeasonID    int64     `json:"season_id"`
	AmountCents int64     `json:"amount_cents"`
	Method      string    `json:"method"`
	Notes       *string   `json:"notes"`
	CreatedAt   time.Time `json:"created_at"`
	SellerName  string    `json:"seller_name"`
}

func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements, arg.SeasonID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsRow{}
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SeasonID,
			&i.AmountCents,
			&i.Method,
			&i.Notes,
			&i.CreatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const myCollectedInFunction = `-- name: MyCollectedInFunction :one
SELECT COALESCE(SUM(s.paid_cents), 0)::bigint
FROM sales s
WHERE s.seller_id = $1::bigint
  AND s.function_id = $2::bigint
  AND NOT s.is_comp
  AND s.voided_at IS NULL
`

type MyCollectedInFunctionParams struct {
	SellerID   int64 `json:"seller_id"`
	FunctionID int64 `json:"function_id"`
}

// Lo que la corista ya tiene cobrado de esa funcion.
func (q *Queries) MyCollectedInFunction(ctx context.Context, arg MyCollectedInFunctionParams) (int64, error) {
	row := q.db.QueryRow(ctx, myCollectedInFunction, arg.SellerID, arg.FunctionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const myPendingSales = `-- name: MyPendingSales :many
SELECT
  s.id, s.code, s.buyer_name, s.quantity, s.created_at,
  (s.amount_cents - s.paid_cents)::bigint AS balance_cents,
  (s.buyer_email IS NOT NULL)::boolean AS has_email
FROM sales s
JOIN functions f ON s.function_id = f.id
WHERE s.seller_id = $1::bigint
  AND s.voided_at IS NULL
  AND NOT s.is_comp
  AND (
    s.amount_cents > s.paid_cents
    OR (s.buyer_email IS NULL AND f.starts_at > now())
  )
ORDER BY (s.amount_cents > s.paid_cents) DESC, s.created_at
LIMIT $2::integer
`

type MyPendingSalesParams struct {
	SellerID int64 `json:"seller_id"`
	Max      int32 `json:"max"`
}

type MyPendingSalesRow struct {
	ID           int64     `json:"id"`
	Code         string    `json:"code"`
	BuyerName    string    `json:"buyer_name"`
	Quantity     int32     `json:"quantity"`
	CreatedAt    time.Time `json:"created_at"`
	BalanceCents int64     `json:"balance_cents"`
	HasEmail     bool      `json:"has_email"`
}

// Lo que a la corista le falta resolver: cobrar lo que le deben, y compartir
// el link de las ventas sin email. Lo segundo solo si la funcion todavia no
// paso: una entrada de una funcion que ya fue no hay que compartirla. Primero
// lo que tiene plata de por medio, y dentro de cada grupo lo mas viejo.
func (q *Queries) MyPendingSales(ctx context.Context, arg MyPendingSalesParams) ([]MyPendingSalesRow, error) {
	rows, err := q.db.Query(ctx, myPendingSales, arg.SellerID, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MyPendingSalesRow{}
	for rows.Next() {
		var i MyPendingSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuyerName,
			&i.Quantity,
			&i.CreatedAt,
			&i.BalanceCents,
			&i.HasEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentSales = `-- name: RecentSales :many

SELECT
  s.id, s.buyer_name, s.quantity, s.amount_cents, s.paid_cents,
  s.payment_status, s.payment_method, s.is_comp, s.voided_at, s.created_at,
  f.name AS function_name, f.venue AS function_venue,
  u.name AS seller_name
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN users u ON s.seller_id = u.id
WHERE s.voided_at IS NULL
  AND ($1::bigint IS NULL OR s.seller_id = $1::bigint)
ORDER BY s.created_at DESC
LIMIT $2::integer
`

type RecentSalesParams struct {
	SellerID *int64 `json:"seller_id"`
	Max      int32  `json:"max"`
}

type RecentSalesRow struct {
	ID            int64      `json:"id"`
	BuyerName     string     `json:"buyer_name"`
	Quantity      int32      `json:"quantity"`
	AmountCents   int64      `json:"amount_cents"`
	PaidCents     int64      `json:"paid_cents"`
	PaymentStatus string     `json:"payment_status"`
	PaymentMethod *string    `json:"payment_method"`
	IsComp        bool       `json:"is_comp"`
	VoidedAt      *time.Time `json:"voided_at"`
	CreatedAt     time.Time  `json:"created_at"`
	FunctionName  *string    `json:"function_name"`
	FunctionVenue string     `json:"function_venue"`
	SellerName    string     `json:"seller_name"`
}

// ============================================================================
// Home por rol (C12)
// ============================================================================
// Las ultimas ventas para la home. Sin cursor ni filtros: son tres filas.
func (q *Queries) RecentSales(ctx context.Context, arg RecentSalesParams) ([]RecentSalesRow, error) {
	rows, err := q.db.Query(ctx, recentSales, arg.SellerID, arg.Max)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentSalesRow{}
	for rows.Next() {
		var i RecentSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerName,
			&i.Quantity,
			&i.AmountCents,
			&i.PaidCents,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.IsComp,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.FunctionName,
			&i.FunctionVenue,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesReport = `-- name: SalesReport :many
SELECT
  s.function_id,
  f.venue AS function_venue,
  f.starts_at AS function_starts_at,
  f.name AS function_name,
  s.seller_id,
  u.name AS seller_name,
  COALESCE(SUM(s.quantity) FILTER (WHERE NOT s.is_comp), 0)::bigint AS tickets_sold,
  COALESCE(SUM(s.quantity) FILTER (WHERE s.is_comp), 0)::bigint AS comp_tickets,
  COALESCE(SUM(s.paid_cents) FILTER (WHERE NOT s.is_comp), 0)::bigint AS paid_cents,
  COALESCE(SUM(s.amount_cents) FILTER (WHERE s.payment_status = 'pending' AND NOT s.is_comp), 0)::bigint AS pending_cents
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN users u ON s.seller_id = u.id
WHERE s.voided_at IS NULL
  AND ($1::bigint IS NULL OR s.function_id = $1::bigint)
  AND ($2::bigint IS NULL OR s.seller_id = $2::bigint)
GROUP BY s.function_id, f.id, s.seller_id, u.id
ORDER BY f.starts_at, u.name
`

type SalesReportParams struct {
	FunctionID *int64 `json:"function_id"`
	SellerID   *int64 `json:"seller_id"`
}

type SalesReportRow struct {
	FunctionID       int64     `json:"function_id"`
	FunctionVenue    string    `json:"function_venue"`
	FunctionStartsAt time.Time `json:"function_starts_at"`
	FunctionName     *string   `json:"function_name"`
	SellerID         int64     `json:"seller_id"`
	SellerName       string    `json:"seller_name"`
	TicketsSold      int64     `json:"tickets_sold"`
	CompTickets      int64     `json:"comp_tickets"`
	PaidCents        int64     `json:"paid_cents"`
	PendingCents     int64     `json:"pending_cents"`
}

// Una fila por funcion x vendedora, con totales y pagas vs. pendientes.
// Las ventas anuladas no cuentan; las cortesias se informan aparte y nunca
// suman plata.
func (q *Queries) SalesReport(ctx context.Context, arg SalesReportParams) ([]SalesReportRow, error) {
	rows, err := q.db.Query(ctx, salesReport, arg.FunctionID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesReportRow{}
	for rows.Next() {
		var i SalesReportRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionVenue,
			&i.FunctionStartsAt,
			&i.FunctionName,
			&i.SellerID,
			&i.SellerName,
			&i.TicketsSold,
			&i.CompTickets,
			&i.PaidCents,
			&i.PendingCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesTimeline = `-- name: SalesTimeline :many
SELECT
  to_char(s.created_at AT TIME ZONE $1::text, 'YYYY-MM-DD') AS day,
  count(t.id)::bigint AS tickets
FROM tickets t
JOIN sales s ON t.sale_id = s.id
JOIN functions f ON s.function_id = f.id
WHERE f.season_id = $2::bigint
  AND t.status <> 'void'
  AND s.voided_at IS NULL
  AND s.created_at >= $3::timestamptz
GROUP BY 1
ORDER BY 1
`

type SalesTimelineParams struct {
	Tz       string    `json:"tz"`
	SeasonID int64     `json:"season_id"`
	Since    time.Time `json:"since"`
}

type SalesTimelineRow struct {
	Day     string `json:"day"`
	Tickets int64  `json:"tickets"`
}

// Entradas vendidas por dia (C9). El dia se corta en la zona horaria de la
// app (la misma que usa el handler para la ventana), no en UTC: si no, las
// ventas de la noche caerian en el dia siguiente.
func (q *Queries) SalesTimeline(ctx context.Context, arg SalesTimelineParams) ([]SalesTimelineRow, error) {
	rows, err := q.db.Query(ctx, salesTimeline, arg.Tz, arg.SeasonID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesTimelineRow{}
	for rows.Next() {
		var i SalesTimelineRow
		if err := rows.Scan(&i.Day, &i.Tickets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonMoney = `-- name: SeasonMoney :one

SELECT
  COALESCE(SUM(s.amount_cents), 0)::bigint AS sold_cents,
  COALESCE(SUM(s.paid_cents), 0)::bigint AS collected_cents,
  COALESCE(SUM(s.amount_cents - s.paid_cents), 0)::bigint AS uncollected_cents,
  COUNT(*) FILTER (WHERE s.amount_cents > s.paid_cents)::bigint AS sales_uncollected
FROM sales s
JOIN functions f ON s.function_id = f.id
WHERE f.season_id = $1::bigint
  AND NOT s.is_comp
  AND s.voided_at IS NULL
`

type SeasonMoneyRow struct {
	SoldCents        int64 `json:"sold_cents"`
	CollectedCents   int64 `json:"collected_cents"`
	UncollectedCents int64 `json:"uncollected_cents"`
	SalesUncollected int64 `json:"sales_uncollected"`
}

// ============================================================================
// Direccion minimalista: la plata de la temporada y la comparacion
// ============================================================================
// Los tres pedazos en que se parte lo vendido: lo que la corista ya entrego,
// lo que tiene en la mano sin rendir, y lo que el comprador todavia no pago.
// Las cortesias no suman plata y las anuladas no existen.
func (q *Queries) SeasonMoney(ctx context.Context, seasonID int64) (SeasonMoneyRow, error) {
	row := q.db.QueryRow(ctx, seasonMoney, seasonID)
	var i SeasonMoneyRow
	err := row.Scan(
		&i.SoldCents,
		&i.CollectedCents,
		&i.UncollectedCents,
		&i.SalesUncollected,
	)
	return i, err
}

const seasonSettled = `-- name: SeasonSettled :one
SELECT COALESCE(SUM(amount_cents), 0)::bigint
FROM settlements
WHERE season_id = $1::bigint
`

func (q *Queries) SeasonSettled(ctx context.Context, seasonID int64) (int64, error) {
	row := q.db.QueryRow(ctx, seasonSettled, seasonID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sellerDebtSources = `-- name: SellerDebtSources :many

SELECT
  s.id, s.buyer_name, s.quantity, s.paid_cents,
  f.name AS function_name,
  f.venue AS function_venue,
  (SELECT MAX(p.created_at) FROM sale_payments p WHERE p.sale_id = s.id)::timestamptz AS paid_at
FROM sales s
JOIN functions f ON s.function_id = f.id
WHERE s.seller_id = $1::bigint
  AND f.season_id = $2::bigint
  AND s.voided_at IS NULL
  AND NOT s.is_comp
  AND s.paid_cents > 0
ORDER BY paid_at DESC NULLS LAST, s.id DESC
`

type SellerDebtSourcesParams struct {
	SellerID int64 `json:"seller_id"`
	SeasonID int64 `json:"season_id"`
}

type SellerDebtSourcesRow struct {
	ID            int64     `json:"id"`
	BuyerName     string    `json:"buyer_name"`
	Quantity      int32     `json:"quantity"`
	PaidCents     int64     `json:"paid_cents"`
	FunctionName  *string   `json:"function_name"`
	FunctionVenue string    `json:"function_venue"`
	PaidAt        time.Time `json:"paid_at"`
}

// ============================================================================
// Detalle de rendicion de una corista
// ============================================================================
// De donde sale la deuda: las ventas que la corista ya cobro, con cuanto
// cobro de cada una y cuando fue el ultimo cobro. Ordenadas por fecha de
// cobro descendente: lo mas fresco arriba, que es de lo que se acuerda.
func (q *Queries) SellerDebtSources(ctx context.Context, arg SellerDebtSourcesParams) ([]SellerDebtSourcesRow, error) {
	rows, err := q.db.Query(ctx, sellerDebtSources, arg.SellerID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SellerDebtSourcesRow{}
	for rows.Next() {
		var i SellerDebtSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerName,
			&i.Quantity,
			&i.PaidCents,
			&i.FunctionName,
			&i.FunctionVenue,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sellerSeasonStats = `-- name: SellerSeasonStats :one
SELECT
  COUNT(*) FILTER (WHERE s.paid_cents > 0)::bigint AS paid_sales,
  COALESCE(SUM(s.quantity) FILTER (WHERE NOT s.is_comp), 0)::bigint AS tickets_sold,
  COALESCE(SUM(s.amount_cents - s.paid_cents), 0)::bigint AS uncollected_cents,
  COALESCE(MIN((SELECT MIN(p.created_at) FROM sale_payments p WHERE p.sale_id = s.id)),
           '0001-01-01'::timestamptz)::timestamptz AS first_paid_at,
  COALESCE(MAX((SELECT MAX(p.created_at) FROM sale_payments p WHERE p.sale_id = s.id)),
           '0001-01-01'::timestamptz)::timestamptz AS last_paid_at
FROM sales s
JOIN functions f ON s.function_id = f.id
WHERE s.seller_id = $1::bigint
  AND f.season_id = $2::bigint
  AND s.voided_at IS NULL
  AND NOT s.is_comp
`

type SellerSeasonStatsParams struct {
	SellerID int64 `json:"seller_id"`
	SeasonID int64 `json:"season_id"`
}

type SellerSeasonStatsRow struct {
	PaidSales        int64     `json:"paid_sales"`
	TicketsSold      int64     `json:"tickets_sold"`
	UncollectedCents int64     `json:"uncollected_cents"`
	FirstPaidAt      time.Time `json:"first_paid_at"`
	LastPaidAt       time.Time `json:"last_paid_at"`
}

// Los numeros del encabezado: cuantas ventas cobro, desde cuando, y cuanto le
// deben los compradores (que no es exigible todavia).
func (q *Queries) SellerSeasonStats(ctx context.Context, arg SellerSeasonStatsParams) (SellerSeasonStatsRow, error) {
	row := q.db.QueryRow(ctx, sellerSeasonStats, arg.SellerID, arg.SeasonID)
	var i SellerSeasonStatsRow
	err := row.Scan(
		&i.PaidSales,
		&i.TicketsSold,
		&i.UncollectedCents,
		&i.FirstPaidAt,
		&i.LastPaidAt,
	)
	return i, err
}

const settlementsReport = `-- name: SettlementsReport :many
WITH collected AS (
  SELECT s.seller_id,
         COALESCE(SUM(s.paid_cents), 0)::bigint AS paid_cents,
         COALESCE(SUM(s.amount_cents - s.paid_cents), 0)::bigint AS pending_cents
  FROM sales s
  JOIN functions f ON s.function_id = f.id
  WHERE f.season_id = $1::bigint
    AND NOT s.is_comp
    AND s.voided_at IS NULL
  GROUP BY s.seller_id
), settled AS (
  SELECT seller_id, COALESCE(SUM(amount_cents), 0)::bigint AS cents
  FROM settlements
  WHERE season_id = $1::bigint
  GROUP BY seller_id
)
SELECT
  u.id AS seller_id,
  u.name AS seller_name,
  COALESCE(c.paid_cents, 0)::bigint AS collected_cents,
  COALESCE(c.pending_cents, 0)::bigint AS pending_cents,
  COALESCE(st.cents, 0)::bigint AS settled_cents
FROM users u
LEFT JOIN collected c ON c.seller_id = u.id
LEFT JOIN settled st ON st.seller_id = u.id
WHERE u.role = 'seller' OR c.seller_id IS NOT NULL OR st.seller_id IS NOT NULL
ORDER BY u.name
`

type SettlementsReportRow struct {
	SellerID       int64  `json:"seller_id"`
	SellerName     string `json:"seller_name"`
	CollectedCents int64  `json:"collected_cents"`
	PendingCents   int64  `json:"pending_cents"`
	SettledCents   int64  `json:"settled_cents"`
}

// Por vendedora de una temporada: cobrado (plata que la corista tiene en la
// mano, cobros parciales incluidos; sin cortesias ni anuladas), pendiente de
// cobro, y rendido. El saldo a rendir es collected - settled (spec §4). Lista
// a toda vendedora, mas cualquier otro usuario con movimientos (p. ej. el
// admin si vendio).
func (q *Queries) SettlementsReport(ctx context.Context, seasonID int64) ([]SettlementsReportRow, error) {
	rows, err := q.db.Query(ctx, settlementsReport, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsReportRow{}
	for rows.Next() {
		var i SettlementsReportRow
		if err := rows.Scan(
			&i.SellerID,
			&i.SellerName,
			&i.CollectedCents,
			&i.PendingCents,
			&i.SettledCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
