// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"
	"time"
)

const attendanceEntries = `-- name: AttendanceEntries :many
SELECT
  s.buyer_name,
  seller.name AS seller_name,
  s.is_comp,
  c.created_at,
  c.method,
  checker.name AS by_name
FROM checkins c
JOIN tickets t ON c.ticket_id = t.id
JOIN sales s ON t.sale_id = s.id
JOIN users seller ON s.seller_id = seller.id
JOIN users checker ON c.user_id = checker.id
WHERE s.function_id = $1::bigint
ORDER BY c.created_at DESC
`

type AttendanceEntriesRow struct {
	BuyerName  string    `json:"buyer_name"`
	SellerName string    `json:"seller_name"`
	IsComp     bool      `json:"is_comp"`
	CreatedAt  time.Time `json:"created_at"`
	Method     string    `json:"method"`
	ByName     string    `json:"by_name"`
}

// Quien entro y a que hora, lo mas nuevo primero.
func (q *Queries) AttendanceEntries(ctx context.Context, functionID int64) ([]AttendanceEntriesRow, error) {
	rows, err := q.db.Query(ctx, attendanceEntries, functionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceEntriesRow{}
	for rows.Next() {
		var i AttendanceEntriesRow
		if err := rows.Scan(
			&i.BuyerName,
			&i.SellerName,
			&i.IsComp,
			&i.CreatedAt,
			&i.Method,
			&i.ByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (seller_id, season_id, amount_cents, method, notes)
VALUES (
  $1::bigint,
  $2::bigint,
  $3::bigint,
  $4::text,
  $5
)
RETURNING id, seller_id, season_id, amount_cents, method, notes, created_at
`

type CreateSettlementParams struct {
	SellerID    int64   `json:"seller_id"`
	SeasonID    int64   `json:"season_id"`
	AmountCents int64   `json:"amount_cents"`
	Method      string  `json:"method"`
	Notes       *string `json:"notes"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.SellerID,
		arg.SeasonID,
		arg.AmountCents,
		arg.Method,
		arg.Notes,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.SellerID,
		&i.SeasonID,
		&i.AmountCents,
		&i.Method,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listSettlements = `-- name: ListSettlements :many
SELECT st.id, st.seller_id, st.season_id, st.amount_cents, st.method, st.notes, st.created_at, u.name AS seller_name
FROM settlements st
JOIN users u ON st.seller_id = u.id
WHERE st.season_id = $1::bigint
  AND ($2::bigint IS NULL OR st.seller_id = $2::bigint)
ORDER BY st.created_at DESC
`

type ListSettlementsParams struct {
	SeasonID int64  `json:"season_id"`
	SellerID *int64 `json:"seller_id"`
}

type ListSettlementsRow struct {
	ID          int64     `json:"id"`
	SellerID    int64     `json:"seller_id"`
	SeasonID    int64     `json:"season_id"`
	AmountCents int64     `json:"amount_cents"`
	Method      string    `json:"method"`
	Notes       *string   `json:"notes"`
	CreatedAt   time.Time `json:"created_at"`
	SellerName  string    `json:"seller_name"`
}

func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements, arg.SeasonID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsRow{}
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.SellerID,
			&i.SeasonID,
			&i.AmountCents,
			&i.Method,
			&i.Notes,
			&i.CreatedAt,
			&i.SellerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesReport = `-- name: SalesReport :many
SELECT
  s.function_id,
  f.venue AS function_venue,
  f.starts_at AS function_starts_at,
  f.name AS function_name,
  s.seller_id,
  u.name AS seller_name,
  COALESCE(SUM(s.quantity) FILTER (WHERE NOT s.is_comp), 0)::bigint AS tickets_sold,
  COALESCE(SUM(s.quantity) FILTER (WHERE s.is_comp), 0)::bigint AS comp_tickets,
  COALESCE(SUM(s.amount_cents) FILTER (WHERE s.payment_status = 'paid' AND NOT s.is_comp), 0)::bigint AS paid_cents,
  COALESCE(SUM(s.amount_cents) FILTER (WHERE s.payment_status = 'pending' AND NOT s.is_comp), 0)::bigint AS pending_cents
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN users u ON s.seller_id = u.id
WHERE s.voided_at IS NULL
  AND ($1::bigint IS NULL OR s.function_id = $1::bigint)
  AND ($2::bigint IS NULL OR s.seller_id = $2::bigint)
GROUP BY s.function_id, f.id, s.seller_id, u.id
ORDER BY f.starts_at, u.name
`

type SalesReportParams struct {
	FunctionID *int64 `json:"function_id"`
	SellerID   *int64 `json:"seller_id"`
}

type SalesReportRow struct {
	FunctionID       int64     `json:"function_id"`
	FunctionVenue    string    `json:"function_venue"`
	FunctionStartsAt time.Time `json:"function_starts_at"`
	FunctionName     *string   `json:"function_name"`
	SellerID         int64     `json:"seller_id"`
	SellerName       string    `json:"seller_name"`
	TicketsSold      int64     `json:"tickets_sold"`
	CompTickets      int64     `json:"comp_tickets"`
	PaidCents        int64     `json:"paid_cents"`
	PendingCents     int64     `json:"pending_cents"`
}

// Una fila por funcion x vendedora, con totales y pagas vs. pendientes.
// Las ventas anuladas no cuentan; las cortesias se informan aparte y nunca
// suman plata.
func (q *Queries) SalesReport(ctx context.Context, arg SalesReportParams) ([]SalesReportRow, error) {
	rows, err := q.db.Query(ctx, salesReport, arg.FunctionID, arg.SellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesReportRow{}
	for rows.Next() {
		var i SalesReportRow
		if err := rows.Scan(
			&i.FunctionID,
			&i.FunctionVenue,
			&i.FunctionStartsAt,
			&i.FunctionName,
			&i.SellerID,
			&i.SellerName,
			&i.TicketsSold,
			&i.CompTickets,
			&i.PaidCents,
			&i.PendingCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settlementsReport = `-- name: SettlementsReport :many
WITH collected AS (
  SELECT s.seller_id,
         COALESCE(SUM(s.amount_cents) FILTER (WHERE s.payment_status = 'paid'), 0)::bigint AS paid_cents,
         COALESCE(SUM(s.amount_cents) FILTER (WHERE s.payment_status = 'pending'), 0)::bigint AS pending_cents
  FROM sales s
  JOIN functions f ON s.function_id = f.id
  WHERE f.season_id = $1::bigint
    AND NOT s.is_comp
    AND s.voided_at IS NULL
  GROUP BY s.seller_id
), settled AS (
  SELECT seller_id, COALESCE(SUM(amount_cents), 0)::bigint AS cents
  FROM settlements
  WHERE season_id = $1::bigint
  GROUP BY seller_id
)
SELECT
  u.id AS seller_id,
  u.name AS seller_name,
  COALESCE(c.paid_cents, 0)::bigint AS collected_cents,
  COALESCE(c.pending_cents, 0)::bigint AS pending_cents,
  COALESCE(st.cents, 0)::bigint AS settled_cents
FROM users u
LEFT JOIN collected c ON c.seller_id = u.id
LEFT JOIN settled st ON st.seller_id = u.id
WHERE u.role = 'seller' OR c.seller_id IS NOT NULL OR st.seller_id IS NOT NULL
ORDER BY u.name
`

type SettlementsReportRow struct {
	SellerID       int64  `json:"seller_id"`
	SellerName     string `json:"seller_name"`
	CollectedCents int64  `json:"collected_cents"`
	PendingCents   int64  `json:"pending_cents"`
	SettledCents   int64  `json:"settled_cents"`
}

// Por vendedora de una temporada: cobrado (ventas pagas, sin cortesias ni
// anuladas), pendiente de cobro, y rendido. El saldo a rendir es
// collected - settled (spec §4). Lista a toda vendedora, mas cualquier otro
// usuario con movimientos (p. ej. el admin si vendio).
func (q *Queries) SettlementsReport(ctx context.Context, seasonID int64) ([]SettlementsReportRow, error) {
	rows, err := q.db.Query(ctx, settlementsReport, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsReportRow{}
	for rows.Next() {
		var i SettlementsReportRow
		if err := rows.Scan(
			&i.SellerID,
			&i.SellerName,
			&i.CollectedCents,
			&i.PendingCents,
			&i.SettledCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
