// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveTickets = `-- name: CountActiveTickets :one
SELECT count(*) FROM tickets t
JOIN sales s ON t.sale_id = s.id
WHERE s.function_id = $1 AND t.status <> 'void'
`

// Entradas que ocupan cupo: todas las no anuladas de la funcion.
func (q *Queries) CountActiveTickets(ctx context.Context, functionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTickets, functionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsBySaleAndStatus = `-- name: CountTicketsBySaleAndStatus :one
SELECT count(*) FROM tickets WHERE sale_id = $1 AND status = $2::text
`

type CountTicketsBySaleAndStatusParams struct {
	SaleID int64  `json:"sale_id"`
	Status string `json:"status"`
}

func (q *Queries) CountTicketsBySaleAndStatus(ctx context.Context, arg CountTicketsBySaleAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsBySaleAndStatus, arg.SaleID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sales (function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, is_comp, notes)
VALUES (
  $1::bigint,
  $2::bigint,
  $3::text,
  $4::text,
  $5,
  $6,
  $7::integer,
  $8::bigint,
  $9::boolean,
  $10
)
RETURNING id, function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, payment_status, payment_method, is_comp, notes, voided_at, created_at, paid_cents
`

type CreateSaleParams struct {
	FunctionID  int64   `json:"function_id"`
	SellerID    int64   `json:"seller_id"`
	Code        string  `json:"code"`
	BuyerName   string  `json:"buyer_name"`
	BuyerEmail  *string `json:"buyer_email"`
	BuyerPhone  *string `json:"buyer_phone"`
	Quantity    int32   `json:"quantity"`
	AmountCents int64   `json:"amount_cents"`
	IsComp      bool    `json:"is_comp"`
	Notes       *string `json:"notes"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.FunctionID,
		arg.SellerID,
		arg.Code,
		arg.BuyerName,
		arg.BuyerEmail,
		arg.BuyerPhone,
		arg.Quantity,
		arg.AmountCents,
		arg.IsComp,
		arg.Notes,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const createSalePayment = `-- name: CreateSalePayment :one

INSERT INTO sale_payments (sale_id, amount_cents, method, user_id)
VALUES ($1::bigint, $2::bigint,
        $3::text, $4::bigint)
RETURNING id, sale_id, amount_cents, method, user_id, created_at
`

type CreateSalePaymentParams struct {
	SaleID      int64  `json:"sale_id"`
	AmountCents int64  `json:"amount_cents"`
	Method      string `json:"method"`
	UserID      int64  `json:"user_id"`
}

// ============================================================================
// Cobros de una venta (parciales o totales)
// ============================================================================
func (q *Queries) CreateSalePayment(ctx context.Context, arg CreateSalePaymentParams) (SalePayment, error) {
	row := q.db.QueryRow(ctx, createSalePayment,
		arg.SaleID,
		arg.AmountCents,
		arg.Method,
		arg.UserID,
	)
	var i SalePayment
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.AmountCents,
		&i.Method,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (sale_id, code)
VALUES ($1::bigint, $2::text)
RETURNING id, sale_id, code, status, created_at
`

type CreateTicketParams struct {
	SaleID int64  `json:"sale_id"`
	Code   string `json:"code"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.SaleID, arg.Code)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSalePayment = `-- name: DeleteSalePayment :one
DELETE FROM sale_payments
WHERE id = $1::bigint AND sale_id = $2::bigint
RETURNING id, sale_id, amount_cents, method, user_id, created_at
`

type DeleteSalePaymentParams struct {
	ID     int64 `json:"id"`
	SaleID int64 `json:"sale_id"`
}

func (q *Queries) DeleteSalePayment(ctx context.Context, arg DeleteSalePaymentParams) (SalePayment, error) {
	row := q.db.QueryRow(ctx, deleteSalePayment, arg.ID, arg.SaleID)
	var i SalePayment
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.AmountCents,
		&i.Method,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSalePayments = `-- name: DeleteSalePayments :exec
DELETE FROM sale_payments WHERE sale_id = $1::bigint
`

func (q *Queries) DeleteSalePayments(ctx context.Context, saleID int64) error {
	_, err := q.db.Exec(ctx, deleteSalePayments, saleID)
	return err
}

const getFunctionForUpdate = `-- name: GetFunctionForUpdate :one
SELECT id, season_id, name, venue, starts_at, capacity, price_cents, created_at FROM functions WHERE id = $1 FOR UPDATE
`

// Lockea la fila de la funcion para serializar la validacion de cupo entre
// ventas concurrentes (spec §4).
func (q *Queries) GetFunctionForUpdate(ctx context.Context, id int64) (Function, error) {
	row := q.db.QueryRow(ctx, getFunctionForUpdate, id)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getSale = `-- name: GetSale :one
SELECT id, function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, payment_status, payment_method, is_comp, notes, voided_at, created_at, paid_cents FROM sales WHERE id = $1
`

func (q *Queries) GetSale(ctx context.Context, id int64) (Sale, error) {
	row := q.db.QueryRow(ctx, getSale, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const getSaleByCode = `-- name: GetSaleByCode :one
SELECT id, function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, payment_status, payment_method, is_comp, notes, voided_at, created_at, paid_cents FROM sales WHERE code = $1::text
`

func (q *Queries) GetSaleByCode(ctx context.Context, code string) (Sale, error) {
	row := q.db.QueryRow(ctx, getSaleByCode, code)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, sale_id, code, status, created_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT id, sale_id, code, status, created_at FROM tickets WHERE code = $1::text
`

func (q *Queries) GetTicketByCode(ctx context.Context, code string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByCode, code)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listEmailSendsBySale = `-- name: ListEmailSendsBySale :many
SELECT id, sale_id, recipient, status, error, created_at FROM email_sends WHERE sale_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEmailSendsBySale(ctx context.Context, saleID int64) ([]EmailSend, error) {
	rows, err := q.db.Query(ctx, listEmailSendsBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailSend{}
	for rows.Next() {
		var i EmailSend
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.Recipient,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalePayments = `-- name: ListSalePayments :many
SELECT p.id, p.sale_id, p.amount_cents, p.method, p.user_id, p.created_at, u.name AS by_name
FROM sale_payments p
JOIN users u ON u.id = p.user_id
WHERE p.sale_id = $1::bigint
ORDER BY p.created_at, p.id
`

type ListSalePaymentsRow struct {
	ID          int64     `json:"id"`
	SaleID      int64     `json:"sale_id"`
	AmountCents int64     `json:"amount_cents"`
	Method      string    `json:"method"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	ByName      string    `json:"by_name"`
}

func (q *Queries) ListSalePayments(ctx context.Context, saleID int64) ([]ListSalePaymentsRow, error) {
	rows, err := q.db.Query(ctx, listSalePayments, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalePaymentsRow{}
	for rows.Next() {
		var i ListSalePaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.AmountCents,
			&i.Method,
			&i.UserID,
			&i.CreatedAt,
			&i.ByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesDetailed = `-- name: ListSalesDetailed :many
SELECT
  s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents,
  f.venue AS function_venue,
  f.starts_at AS function_starts_at,
  f.name AS function_name,
  u.name AS seller_name,
  count(t.id) FILTER (WHERE t.status <> 'void') AS active_tickets
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN users u ON s.seller_id = u.id
LEFT JOIN tickets t ON t.sale_id = s.id
WHERE ($1::bigint IS NULL OR s.seller_id = $1::bigint)
  AND ($2::bigint IS NULL OR s.function_id = $2::bigint)
GROUP BY s.id, f.id, u.id
ORDER BY s.created_at DESC
`

type ListSalesDetailedParams struct {
	SellerID   *int64 `json:"seller_id"`
	FunctionID *int64 `json:"function_id"`
}

type ListSalesDetailedRow struct {
	ID               int64      `json:"id"`
	FunctionID       int64      `json:"function_id"`
	SellerID         int64      `json:"seller_id"`
	Code             string     `json:"code"`
	BuyerName        string     `json:"buyer_name"`
	BuyerEmail       *string    `json:"buyer_email"`
	BuyerPhone       *string    `json:"buyer_phone"`
	Quantity         int32      `json:"quantity"`
	AmountCents      int64      `json:"amount_cents"`
	PaymentStatus    string     `json:"payment_status"`
	PaymentMethod    *string    `json:"payment_method"`
	IsComp           bool       `json:"is_comp"`
	Notes            *string    `json:"notes"`
	VoidedAt         *time.Time `json:"voided_at"`
	CreatedAt        time.Time  `json:"created_at"`
	PaidCents        int64      `json:"paid_cents"`
	FunctionVenue    string     `json:"function_venue"`
	FunctionStartsAt time.Time  `json:"function_starts_at"`
	FunctionName     *string    `json:"function_name"`
	SellerName       string     `json:"seller_name"`
	ActiveTickets    int64      `json:"active_tickets"`
}

// Listado para la UI: la venta con su funcion, vendedora y conteo de tickets
// vivos. Filtros opcionales por vendedora y por funcion.
func (q *Queries) ListSalesDetailed(ctx context.Context, arg ListSalesDetailedParams) ([]ListSalesDetailedRow, error) {
	rows, err := q.db.Query(ctx, listSalesDetailed, arg.SellerID, arg.FunctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesDetailedRow{}
	for rows.Next() {
		var i ListSalesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.FunctionID,
			&i.SellerID,
			&i.Code,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.BuyerPhone,
			&i.Quantity,
			&i.AmountCents,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.IsComp,
			&i.Notes,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.PaidCents,
			&i.FunctionVenue,
			&i.FunctionStartsAt,
			&i.FunctionName,
			&i.SellerName,
			&i.ActiveTickets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsBySale = `-- name: ListTicketsBySale :many
SELECT id, sale_id, code, status, created_at FROM tickets WHERE sale_id = $1 ORDER BY id
`

func (q *Queries) ListTicketsBySale(ctx context.Context, saleID int64) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalcSalePayment = `-- name: RecalcSalePayment :one
UPDATE sales s
SET paid_cents = c.total,
    payment_status = CASE WHEN c.total >= s.amount_cents AND c.total > 0 THEN 'paid' ELSE 'pending' END,
    payment_method = c.last_method
FROM (
  SELECT
    COALESCE(SUM(p.amount_cents), 0)::bigint AS total,
    (SELECT p2.method FROM sale_payments p2
     WHERE p2.sale_id = $1::bigint
     ORDER BY p2.created_at DESC, p2.id DESC LIMIT 1) AS last_method
  FROM sale_payments p WHERE p.sale_id = $1::bigint
) c
WHERE s.id = $1::bigint
RETURNING s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents
`

// Recalcula el cache de la venta desde sus cobros: cuanto lleva cobrado, si
// termino de pagar, y con que metodo fue el ultimo cobro (lo que muestra el
// chip). Se llama siempre entera, nunca sumando de a poco, para que el cache
// no pueda separarse del historial.
func (q *Queries) RecalcSalePayment(ctx context.Context, saleID int64) (Sale, error) {
	row := q.db.QueryRow(ctx, recalcSalePayment, saleID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const recordEmailSend = `-- name: RecordEmailSend :one
INSERT INTO email_sends (sale_id, recipient, status, error)
VALUES (
  $1::bigint,
  $2::text,
  $3::text,
  $4
)
RETURNING id, sale_id, recipient, status, error, created_at
`

type RecordEmailSendParams struct {
	SaleID    int64   `json:"sale_id"`
	Recipient string  `json:"recipient"`
	Status    string  `json:"status"`
	Error     *string `json:"error"`
}

func (q *Queries) RecordEmailSend(ctx context.Context, arg RecordEmailSendParams) (EmailSend, error) {
	row := q.db.QueryRow(ctx, recordEmailSend,
		arg.SaleID,
		arg.Recipient,
		arg.Status,
		arg.Error,
	)
	var i EmailSend
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Recipient,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const updateSalePayment = `-- name: UpdateSalePayment :one
UPDATE sales
SET payment_status = $1::text,
    payment_method = $2
WHERE id = $3::bigint
RETURNING id, function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, payment_status, payment_method, is_comp, notes, voided_at, created_at, paid_cents
`

type UpdateSalePaymentParams struct {
	PaymentStatus string  `json:"payment_status"`
	PaymentMethod *string `json:"payment_method"`
	ID            int64   `json:"id"`
}

func (q *Queries) UpdateSalePayment(ctx context.Context, arg UpdateSalePaymentParams) (Sale, error) {
	row := q.db.QueryRow(ctx, updateSalePayment, arg.PaymentStatus, arg.PaymentMethod, arg.ID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const voidSale = `-- name: VoidSale :one
UPDATE sales SET voided_at = now() WHERE id = $1::bigint RETURNING id, function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, payment_status, payment_method, is_comp, notes, voided_at, created_at, paid_cents
`

func (q *Queries) VoidSale(ctx context.Context, id int64) (Sale, error) {
	row := q.db.QueryRow(ctx, voidSale, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const voidTicket = `-- name: VoidTicket :one
UPDATE tickets SET status = 'void' WHERE id = $1::bigint RETURNING id, sale_id, code, status, created_at
`

func (q *Queries) VoidTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, voidTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const voidTicketsOfSale = `-- name: VoidTicketsOfSale :exec
UPDATE tickets SET status = 'void' WHERE sale_id = $1::bigint AND status = 'issued'
`

func (q *Queries) VoidTicketsOfSale(ctx context.Context, saleID int64) error {
	_, err := q.db.Exec(ctx, voidTicketsOfSale, saleID)
	return err
}
