// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales_list.sql

package sqlcgen

import (
	"context"
	"time"
)

const listSalesPage = `-- name: ListSalesPage :many

SELECT
  s.id, s.code, s.buyer_name, s.buyer_email, s.quantity, s.amount_cents,
  s.payment_status, s.payment_method, s.paid_cents, s.is_comp, s.voided_at, s.created_at,
  s.function_id,
  f.venue AS function_venue,
  f.starts_at AS function_starts_at,
  f.name AS function_name,
  u.name AS seller_name,
  -- COALESCE al año 1 = "nunca se envio"; el handler lo convierte a null.
  COALESCE((SELECT max(e.created_at) FROM email_sends e
   WHERE e.sale_id = s.id AND e.status = 'sent'), '0001-01-01'::timestamptz)::timestamptz AS last_email_at
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN users u ON s.seller_id = u.id
WHERE ($1::bigint IS NULL OR s.seller_id = $1::bigint)
  AND ($2::bigint IS NULL OR s.function_id = $2::bigint)
  AND (
    $3::text IS NULL
    OR ($3::text = 'pending' AND NOT s.is_comp AND s.payment_status = 'pending' AND s.voided_at IS NULL)
    OR ($3::text = 'paid'    AND NOT s.is_comp AND s.payment_status = 'paid'    AND s.voided_at IS NULL)
    OR ($3::text = 'comp'    AND s.is_comp AND s.voided_at IS NULL)
  )
  AND (
    $4::text IS NULL
    OR translate(lower(s.buyer_name), 'áéíóúäëïöüñç', 'aeiouaeiounc')
       LIKE '%' || translate(lower($4::text), 'áéíóúäëïöüñç', 'aeiouaeiounc') || '%'
    OR translate(lower(u.name), 'áéíóúäëïöüñç', 'aeiouaeiounc')
       LIKE '%' || translate(lower($4::text), 'áéíóúäëïöüñç', 'aeiouaeiounc') || '%'
  )
  AND (
    $5::timestamptz IS NULL
    OR (f.starts_at, s.id) > ($5::timestamptz, $6::bigint)
  )
ORDER BY f.starts_at, s.id
LIMIT $7::integer
`

type ListSalesPageParams struct {
	SellerID     *int64     `json:"seller_id"`
	FunctionID   *int64     `json:"function_id"`
	Status       *string    `json:"status"`
	Q            *string    `json:"q"`
	CursorStarts *time.Time `json:"cursor_starts"`
	CursorID     *int64     `json:"cursor_id"`
	PageSize     int32      `json:"page_size"`
}

type ListSalesPageRow struct {
	ID               int64      `json:"id"`
	Code             string     `json:"code"`
	BuyerName        string     `json:"buyer_name"`
	BuyerEmail       *string    `json:"buyer_email"`
	Quantity         int32      `json:"quantity"`
	AmountCents      int64      `json:"amount_cents"`
	PaymentStatus    string     `json:"payment_status"`
	PaymentMethod    *string    `json:"payment_method"`
	PaidCents        int64      `json:"paid_cents"`
	IsComp           bool       `json:"is_comp"`
	VoidedAt         *time.Time `json:"voided_at"`
	CreatedAt        time.Time  `json:"created_at"`
	FunctionID       int64      `json:"function_id"`
	FunctionVenue    string     `json:"function_venue"`
	FunctionStartsAt time.Time  `json:"function_starts_at"`
	FunctionName     *string    `json:"function_name"`
	SellerName       string     `json:"seller_name"`
	LastEmailAt      time.Time  `json:"last_email_at"`
}

// Listado escalable de ventas (CAMBIOS_V2 §C3).
//
// Busqueda insensible a mayusculas y acentos con translate() (sin extension
// unaccent: portable a cualquier Postgres; ver DECISIONS.md). El mismo
// normalizado se aplica a ambos lados del LIKE.
//
// Paginacion por keyset (f.starts_at, s.id): los grupos por funcion quedan
// contiguos entre paginas.
func (q *Queries) ListSalesPage(ctx context.Context, arg ListSalesPageParams) ([]ListSalesPageRow, error) {
	rows, err := q.db.Query(ctx, listSalesPage,
		arg.SellerID,
		arg.FunctionID,
		arg.Status,
		arg.Q,
		arg.CursorStarts,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesPageRow{}
	for rows.Next() {
		var i ListSalesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.Quantity,
			&i.AmountCents,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.PaidCents,
			&i.IsComp,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.FunctionID,
			&i.FunctionVenue,
			&i.FunctionStartsAt,
			&i.FunctionName,
			&i.SellerName,
			&i.LastEmailAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesSummary = `-- name: SalesSummary :one
SELECT
  COALESCE(SUM(s.quantity) FILTER (WHERE NOT s.is_comp AND s.voided_at IS NULL), 0)::bigint AS tickets_sold,
  -- Cobrado y por cobrar salen de lo efectivamente cobrado: una venta con un
  -- cobro parcial suma su parte de cada lado, no todo de uno.
  COALESCE(SUM(s.paid_cents) FILTER (WHERE NOT s.is_comp AND s.voided_at IS NULL), 0)::bigint AS paid_cents,
  COALESCE(SUM(s.amount_cents - s.paid_cents) FILTER (WHERE NOT s.is_comp AND s.voided_at IS NULL), 0)::bigint AS pending_cents,
  COUNT(*)::bigint AS total_count,
  COUNT(*) FILTER (WHERE s.payment_status = 'pending' AND NOT s.is_comp AND s.voided_at IS NULL)::bigint AS pending_count
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN users u ON s.seller_id = u.id
WHERE ($1::bigint IS NULL OR s.seller_id = $1::bigint)
  AND ($2::bigint IS NULL OR s.function_id = $2::bigint)
  AND (
    $3::text IS NULL
    OR translate(lower(s.buyer_name), 'áéíóúäëïöüñç', 'aeiouaeiounc')
       LIKE '%' || translate(lower($3::text), 'áéíóúäëïöüñç', 'aeiouaeiounc') || '%'
    OR translate(lower(u.name), 'áéíóúäëïöüñç', 'aeiouaeiounc')
       LIKE '%' || translate(lower($3::text), 'áéíóúäëïöüñç', 'aeiouaeiounc') || '%'
  )
`

type SalesSummaryParams struct {
	SellerID   *int64  `json:"seller_id"`
	FunctionID *int64  `json:"function_id"`
	Q          *string `json:"q"`
}

type SalesSummaryRow struct {
	TicketsSold  int64 `json:"tickets_sold"`
	PaidCents    int64 `json:"paid_cents"`
	PendingCents int64 `json:"pending_cents"`
	TotalCount   int64 `json:"total_count"`
	PendingCount int64 `json:"pending_count"`
}

// Resumen del mismo alcance (vendedora/funcion/busqueda) SIN el filtro de
// estado ni el cursor: alimenta la tira de arriba y los contadores de chips.
func (q *Queries) SalesSummary(ctx context.Context, arg SalesSummaryParams) (SalesSummaryRow, error) {
	row := q.db.QueryRow(ctx, salesSummary, arg.SellerID, arg.FunctionID, arg.Q)
	var i SalesSummaryRow
	err := row.Scan(
		&i.TicketsSold,
		&i.PaidCents,
		&i.PendingCents,
		&i.TotalCount,
		&i.PendingCount,
	)
	return i, err
}
