// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package sqlcgen

import (
	"context"
	"time"
)

const countActiveTickets = `-- name: CountActiveTickets :one
SELECT count(*) FROM tickets t
JOIN sales s ON t.sale_id = s.id
JOIN functions f ON f.id = s.function_id
JOIN seasons se ON se.id = f.season_id
WHERE s.function_id = $1::bigint
  AND se.organization_id = $2::bigint
  AND t.status <> 'void'
`

type CountActiveTicketsParams struct {
	FunctionID     int64 `json:"function_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Entradas que ocupan cupo: todas las no anuladas de la funcion.
func (q *Queries) CountActiveTickets(ctx context.Context, arg CountActiveTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTickets, arg.FunctionID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSalesBySellerInSeason = `-- name: CountSalesBySellerInSeason :one
SELECT count(*)::bigint FROM sales s
JOIN functions f ON f.id = s.function_id
JOIN seasons se ON se.id = f.season_id
WHERE s.seller_id = $1::bigint
  AND f.season_id = $2::bigint
  AND se.organization_id = $3::bigint
`

type CountSalesBySellerInSeasonParams struct {
	SellerID       int64 `json:"seller_id"`
	SeasonID       int64 `json:"season_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) CountSalesBySellerInSeason(ctx context.Context, arg CountSalesBySellerInSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSalesBySellerInSeason, arg.SellerID, arg.SeasonID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countTicketsBySaleAndStatus = `-- name: CountTicketsBySaleAndStatus :one
SELECT count(*) FROM tickets WHERE sale_id = $1 AND status = $2::text
`

type CountTicketsBySaleAndStatusParams struct {
	SaleID int64  `json:"sale_id"`
	Status string `json:"status"`
}

// El caller ya resolvio la venta con GetSale (acotado).
func (q *Queries) CountTicketsBySaleAndStatus(ctx context.Context, arg CountTicketsBySaleAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsBySaleAndStatus, arg.SaleID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sales (function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, is_comp, notes)
SELECT
  f.id,
  $1::bigint,
  $2::text,
  $3::text,
  $4,
  $5,
  $6::integer,
  $7::bigint,
  $8::boolean,
  $9
FROM functions f
JOIN seasons se ON se.id = f.season_id
WHERE f.id = $10::bigint
  AND se.organization_id = $11::bigint
RETURNING id, function_id, seller_id, code, buyer_name, buyer_email, buyer_phone, quantity, amount_cents, payment_status, payment_method, is_comp, notes, voided_at, created_at, paid_cents
`

type CreateSaleParams struct {
	SellerID       int64   `json:"seller_id"`
	Code           string  `json:"code"`
	BuyerName      string  `json:"buyer_name"`
	BuyerEmail     *string `json:"buyer_email"`
	BuyerPhone     *string `json:"buyer_phone"`
	Quantity       int32   `json:"quantity"`
	AmountCents    int64   `json:"amount_cents"`
	IsComp         bool    `json:"is_comp"`
	Notes          *string `json:"notes"`
	FunctionID     int64   `json:"function_id"`
	OrganizationID int64   `json:"organization_id"`
}

// Solo si la funcion es de la organizacion; si no, no inserta (ErrNoRows).
func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.SellerID,
		arg.Code,
		arg.BuyerName,
		arg.BuyerEmail,
		arg.BuyerPhone,
		arg.Quantity,
		arg.AmountCents,
		arg.IsComp,
		arg.Notes,
		arg.FunctionID,
		arg.OrganizationID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const createSalePayment = `-- name: CreateSalePayment :one

INSERT INTO sale_payments (sale_id, amount_cents, method, user_id)
VALUES ($1::bigint, $2::bigint,
        $3::text, $4::bigint)
RETURNING id, sale_id, amount_cents, method, user_id, created_at
`

type CreateSalePaymentParams struct {
	SaleID      int64  `json:"sale_id"`
	AmountCents int64  `json:"amount_cents"`
	Method      string `json:"method"`
	UserID      int64  `json:"user_id"`
}

// ============================================================================
// Cobros de una venta (parciales o totales)
// ============================================================================
// Todas reciben un sale_id que el handler ya resolvio con GetSale (acotado),
// salvo las de a lote, que usan SalesByIDs (acotado).
func (q *Queries) CreateSalePayment(ctx context.Context, arg CreateSalePaymentParams) (SalePayment, error) {
	row := q.db.QueryRow(ctx, createSalePayment,
		arg.SaleID,
		arg.AmountCents,
		arg.Method,
		arg.UserID,
	)
	var i SalePayment
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.AmountCents,
		&i.Method,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (sale_id, code)
VALUES ($1::bigint, $2::text)
RETURNING id, sale_id, code, status, created_at
`

type CreateTicketParams struct {
	SaleID int64  `json:"sale_id"`
	Code   string `json:"code"`
}

// Se llama justo despues de CreateSale, con un sale_id recien creado por la
// misma transaccion: la venta ya fue verificada.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.SaleID, arg.Code)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSalePayment = `-- name: DeleteSalePayment :one
DELETE FROM sale_payments
WHERE id = $1::bigint AND sale_id = $2::bigint
RETURNING id, sale_id, amount_cents, method, user_id, created_at
`

type DeleteSalePaymentParams struct {
	ID     int64 `json:"id"`
	SaleID int64 `json:"sale_id"`
}

func (q *Queries) DeleteSalePayment(ctx context.Context, arg DeleteSalePaymentParams) (SalePayment, error) {
	row := q.db.QueryRow(ctx, deleteSalePayment, arg.ID, arg.SaleID)
	var i SalePayment
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.AmountCents,
		&i.Method,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSalePayments = `-- name: DeleteSalePayments :exec
DELETE FROM sale_payments WHERE sale_id = $1::bigint
`

func (q *Queries) DeleteSalePayments(ctx context.Context, saleID int64) error {
	_, err := q.db.Exec(ctx, deleteSalePayments, saleID)
	return err
}

const getFunctionForUpdate = `-- name: GetFunctionForUpdate :one

SELECT f.id, f.season_id, f.name, f.venue, f.starts_at, f.capacity, f.price_cents, f.created_at FROM functions f
JOIN seasons se ON se.id = f.season_id
WHERE f.id = $1::bigint
  AND se.organization_id = $2::bigint
FOR UPDATE OF f
`

type GetFunctionForUpdateParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

// sales y tickets cuelgan de functions → seasons (C17 §A.1). Toda consulta
// con sesion exige que la venta sea de la organizacion; una ajena no existe
// (ErrNoRows → 404). Las dos publicas (GetSaleByCode, GetPublicTicket) no
// llevan organizacion: el codigo secreto ya identifica la venta.
// Lockea la fila de la funcion para serializar la validacion de cupo entre
// ventas concurrentes (spec §4).
func (q *Queries) GetFunctionForUpdate(ctx context.Context, arg GetFunctionForUpdateParams) (Function, error) {
	row := q.db.QueryRow(ctx, getFunctionForUpdate, arg.ID, arg.OrganizationID)
	var i Function
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.Name,
		&i.Venue,
		&i.StartsAt,
		&i.Capacity,
		&i.PriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getPublicSale = `-- name: GetPublicSale :one

SELECT s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents,
  f.name AS function_name,
  f.venue AS function_venue,
  f.starts_at AS function_starts_at,
  u.name AS seller_name
FROM sales s
JOIN functions f ON f.id = s.function_id
JOIN users u ON u.id = s.seller_id
WHERE s.code = $1::text
`

type GetPublicSaleRow struct {
	ID               int64      `json:"id"`
	FunctionID       int64      `json:"function_id"`
	SellerID         int64      `json:"seller_id"`
	Code             string     `json:"code"`
	BuyerName        string     `json:"buyer_name"`
	BuyerEmail       *string    `json:"buyer_email"`
	BuyerPhone       *string    `json:"buyer_phone"`
	Quantity         int32      `json:"quantity"`
	AmountCents      int64      `json:"amount_cents"`
	PaymentStatus    string     `json:"payment_status"`
	PaymentMethod    *string    `json:"payment_method"`
	IsComp           bool       `json:"is_comp"`
	Notes            *string    `json:"notes"`
	VoidedAt         *time.Time `json:"voided_at"`
	CreatedAt        time.Time  `json:"created_at"`
	PaidCents        int64      `json:"paid_cents"`
	FunctionName     *string    `json:"function_name"`
	FunctionVenue    string     `json:"function_venue"`
	FunctionStartsAt time.Time  `json:"function_starts_at"`
	SellerName       string     `json:"seller_name"`
}

// ============================================================================
// Paginas publicas (/e/{code}, /t/{code}.png): sin organizacion a proposito.
// No hay sesion; el codigo secreto ya identifica la venta (C17 §A.2).
// ============================================================================
func (q *Queries) GetPublicSale(ctx context.Context, code string) (GetPublicSaleRow, error) {
	row := q.db.QueryRow(ctx, getPublicSale, code)
	var i GetPublicSaleRow
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
		&i.FunctionName,
		&i.FunctionVenue,
		&i.FunctionStartsAt,
		&i.SellerName,
	)
	return i, err
}

const getPublicTicketByCode = `-- name: GetPublicTicketByCode :one
SELECT id, sale_id, code, status, created_at FROM tickets WHERE code = $1::text
`

func (q *Queries) GetPublicTicketByCode(ctx context.Context, code string) (Ticket, error) {
	row := q.db.QueryRow(ctx, getPublicTicketByCode, code)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSale = `-- name: GetSale :one
SELECT s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents FROM sales s
JOIN functions f ON f.id = s.function_id
JOIN seasons se ON se.id = f.season_id
WHERE s.id = $1::bigint
  AND se.organization_id = $2::bigint
`

type GetSaleParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetSale(ctx context.Context, arg GetSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSale, arg.ID, arg.OrganizationID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.sale_id, t.code, t.status, t.created_at FROM tickets t
JOIN sales s ON s.id = t.sale_id
JOIN functions f ON f.id = s.function_id
JOIN seasons se ON se.id = f.season_id
WHERE t.id = $1::bigint
  AND se.organization_id = $2::bigint
`

type GetTicketParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.ID, arg.OrganizationID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT t.id, t.sale_id, t.code, t.status, t.created_at FROM tickets t
JOIN sales s ON s.id = t.sale_id
JOIN functions f ON f.id = s.function_id
JOIN seasons se ON se.id = f.season_id
WHERE t.code = $1::text
  AND se.organization_id = $2::bigint
`

type GetTicketByCodeParams struct {
	Code           string `json:"code"`
	OrganizationID int64  `json:"organization_id"`
}

// Es la de la puerta: un codigo de otra organizacion no existe, aunque sea
// valido. (La pagina publica usa GetPublicTicket.)
func (q *Queries) GetTicketByCode(ctx context.Context, arg GetTicketByCodeParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByCode, arg.Code, arg.OrganizationID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listEmailSendsBySale = `-- name: ListEmailSendsBySale :many
SELECT id, sale_id, recipient, status, error, created_at FROM email_sends WHERE sale_id = $1 ORDER BY created_at DESC
`

// El caller ya resolvio la venta con GetSale (acotado).
func (q *Queries) ListEmailSendsBySale(ctx context.Context, saleID int64) ([]EmailSend, error) {
	rows, err := q.db.Query(ctx, listEmailSendsBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailSend{}
	for rows.Next() {
		var i EmailSend
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.Recipient,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalePayments = `-- name: ListSalePayments :many
SELECT p.id, p.sale_id, p.amount_cents, p.method, p.user_id, p.created_at, u.name AS by_name
FROM sale_payments p
JOIN users u ON u.id = p.user_id
WHERE p.sale_id = $1::bigint
ORDER BY p.created_at, p.id
`

type ListSalePaymentsRow struct {
	ID          int64     `json:"id"`
	SaleID      int64     `json:"sale_id"`
	AmountCents int64     `json:"amount_cents"`
	Method      string    `json:"method"`
	UserID      int64     `json:"user_id"`
	CreatedAt   time.Time `json:"created_at"`
	ByName      string    `json:"by_name"`
}

func (q *Queries) ListSalePayments(ctx context.Context, saleID int64) ([]ListSalePaymentsRow, error) {
	rows, err := q.db.Query(ctx, listSalePayments, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalePaymentsRow{}
	for rows.Next() {
		var i ListSalePaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.AmountCents,
			&i.Method,
			&i.UserID,
			&i.CreatedAt,
			&i.ByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesDetailed = `-- name: ListSalesDetailed :many
SELECT
  s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents,
  f.venue AS function_venue,
  f.starts_at AS function_starts_at,
  f.name AS function_name,
  u.name AS seller_name,
  count(t.id) FILTER (WHERE t.status <> 'void') AS active_tickets
FROM sales s
JOIN functions f ON s.function_id = f.id
JOIN seasons se ON se.id = f.season_id
JOIN users u ON s.seller_id = u.id
LEFT JOIN tickets t ON t.sale_id = s.id
WHERE se.organization_id = $1::bigint
  AND ($2::bigint IS NULL OR s.seller_id = $2::bigint)
  AND ($3::bigint IS NULL OR s.function_id = $3::bigint)
GROUP BY s.id, f.id, u.id
ORDER BY s.created_at DESC
`

type ListSalesDetailedParams struct {
	OrganizationID int64  `json:"organization_id"`
	SellerID       *int64 `json:"seller_id"`
	FunctionID     *int64 `json:"function_id"`
}

type ListSalesDetailedRow struct {
	ID               int64      `json:"id"`
	FunctionID       int64      `json:"function_id"`
	SellerID         int64      `json:"seller_id"`
	Code             string     `json:"code"`
	BuyerName        string     `json:"buyer_name"`
	BuyerEmail       *string    `json:"buyer_email"`
	BuyerPhone       *string    `json:"buyer_phone"`
	Quantity         int32      `json:"quantity"`
	AmountCents      int64      `json:"amount_cents"`
	PaymentStatus    string     `json:"payment_status"`
	PaymentMethod    *string    `json:"payment_method"`
	IsComp           bool       `json:"is_comp"`
	Notes            *string    `json:"notes"`
	VoidedAt         *time.Time `json:"voided_at"`
	CreatedAt        time.Time  `json:"created_at"`
	PaidCents        int64      `json:"paid_cents"`
	FunctionVenue    string     `json:"function_venue"`
	FunctionStartsAt time.Time  `json:"function_starts_at"`
	FunctionName     *string    `json:"function_name"`
	SellerName       string     `json:"seller_name"`
	ActiveTickets    int64      `json:"active_tickets"`
}

// Listado para la UI: la venta con su funcion, vendedora y conteo de tickets
// vivos. Filtros opcionales por vendedora y por funcion.
func (q *Queries) ListSalesDetailed(ctx context.Context, arg ListSalesDetailedParams) ([]ListSalesDetailedRow, error) {
	rows, err := q.db.Query(ctx, listSalesDetailed, arg.OrganizationID, arg.SellerID, arg.FunctionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesDetailedRow{}
	for rows.Next() {
		var i ListSalesDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.FunctionID,
			&i.SellerID,
			&i.Code,
			&i.BuyerName,
			&i.BuyerEmail,
			&i.BuyerPhone,
			&i.Quantity,
			&i.AmountCents,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.IsComp,
			&i.Notes,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.PaidCents,
			&i.FunctionVenue,
			&i.FunctionStartsAt,
			&i.FunctionName,
			&i.SellerName,
			&i.ActiveTickets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsBySale = `-- name: ListTicketsBySale :many
SELECT id, sale_id, code, status, created_at FROM tickets WHERE sale_id = $1 ORDER BY id
`

// Sin organizacion: el caller ya resolvio la venta (GetSale acotado, o
// GetSaleByCode en la pagina publica). Las entradas no tienen dueño propio.
func (q *Queries) ListTicketsBySale(ctx context.Context, saleID int64) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.Code,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalcSalePayment = `-- name: RecalcSalePayment :one
UPDATE sales s
SET paid_cents = c.total,
    payment_status = CASE WHEN c.total >= s.amount_cents AND c.total > 0 THEN 'paid' ELSE 'pending' END,
    payment_method = c.last_method
FROM (
  SELECT
    COALESCE(SUM(p.amount_cents), 0)::bigint AS total,
    (SELECT p2.method FROM sale_payments p2
     WHERE p2.sale_id = $1::bigint
     ORDER BY p2.created_at DESC, p2.id DESC LIMIT 1) AS last_method
  FROM sale_payments p WHERE p.sale_id = $1::bigint
) c
WHERE s.id = $1::bigint
RETURNING s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents
`

// Recalcula el cache de la venta desde sus cobros: cuanto lleva cobrado, si
// termino de pagar, y con que metodo fue el ultimo cobro (lo que muestra el
// chip). Se llama siempre entera, nunca sumando de a poco, para que el cache
// no pueda separarse del historial.
func (q *Queries) RecalcSalePayment(ctx context.Context, saleID int64) (Sale, error) {
	row := q.db.QueryRow(ctx, recalcSalePayment, saleID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const recordEmailSend = `-- name: RecordEmailSend :one
INSERT INTO email_sends (sale_id, recipient, status, error)
VALUES (
  $1::bigint,
  $2::text,
  $3::text,
  $4
)
RETURNING id, sale_id, recipient, status, error, created_at
`

type RecordEmailSendParams struct {
	SaleID    int64   `json:"sale_id"`
	Recipient string  `json:"recipient"`
	Status    string  `json:"status"`
	Error     *string `json:"error"`
}

// El caller ya resolvio la venta con GetSale (acotado).
func (q *Queries) RecordEmailSend(ctx context.Context, arg RecordEmailSendParams) (EmailSend, error) {
	row := q.db.QueryRow(ctx, recordEmailSend,
		arg.SaleID,
		arg.Recipient,
		arg.Status,
		arg.Error,
	)
	var i EmailSend
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Recipient,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const updateSalePayment = `-- name: UpdateSalePayment :one
UPDATE sales s
SET payment_status = $1::text,
    payment_method = $2
FROM functions f
JOIN seasons se ON se.id = f.season_id
WHERE f.id = s.function_id
  AND s.id = $3::bigint
  AND se.organization_id = $4::bigint
RETURNING s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents
`

type UpdateSalePaymentParams struct {
	PaymentStatus  string  `json:"payment_status"`
	PaymentMethod  *string `json:"payment_method"`
	ID             int64   `json:"id"`
	OrganizationID int64   `json:"organization_id"`
}

func (q *Queries) UpdateSalePayment(ctx context.Context, arg UpdateSalePaymentParams) (Sale, error) {
	row := q.db.QueryRow(ctx, updateSalePayment,
		arg.PaymentStatus,
		arg.PaymentMethod,
		arg.ID,
		arg.OrganizationID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const voidSale = `-- name: VoidSale :one
UPDATE sales s SET voided_at = now()
FROM functions f
JOIN seasons se ON se.id = f.season_id
WHERE f.id = s.function_id
  AND s.id = $1::bigint
  AND se.organization_id = $2::bigint
RETURNING s.id, s.function_id, s.seller_id, s.code, s.buyer_name, s.buyer_email, s.buyer_phone, s.quantity, s.amount_cents, s.payment_status, s.payment_method, s.is_comp, s.notes, s.voided_at, s.created_at, s.paid_cents
`

type VoidSaleParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) VoidSale(ctx context.Context, arg VoidSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, voidSale, arg.ID, arg.OrganizationID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.FunctionID,
		&i.SellerID,
		&i.Code,
		&i.BuyerName,
		&i.BuyerEmail,
		&i.BuyerPhone,
		&i.Quantity,
		&i.AmountCents,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.IsComp,
		&i.Notes,
		&i.VoidedAt,
		&i.CreatedAt,
		&i.PaidCents,
	)
	return i, err
}

const voidTicket = `-- name: VoidTicket :one
UPDATE tickets t SET status = 'void'
FROM sales s
JOIN functions f ON f.id = s.function_id
JOIN seasons se ON se.id = f.season_id
WHERE s.id = t.sale_id
  AND t.id = $1::bigint
  AND se.organization_id = $2::bigint
RETURNING t.id, t.sale_id, t.code, t.status, t.created_at
`

type VoidTicketParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) VoidTicket(ctx context.Context, arg VoidTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, voidTicket, arg.ID, arg.OrganizationID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Code,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const voidTicketsOfSale = `-- name: VoidTicketsOfSale :exec
UPDATE tickets SET status = 'void' WHERE sale_id = $1::bigint AND status = 'issued'
`

// El caller ya resolvio la venta con GetSale (acotado).
func (q *Queries) VoidTicketsOfSale(ctx context.Context, saleID int64) error {
	_, err := q.db.Exec(ctx, voidTicketsOfSale, saleID)
	return err
}
