// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package sqlcgen

import (
	"context"
)

const createSeason = `-- name: CreateSeason :one
INSERT INTO seasons (name)
VALUES ($1::text)
RETURNING id, name, is_active, created_at
`

func (q *Queries) CreateSeason(ctx context.Context, name string) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason, name)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAllSeasons = `-- name: DeactivateAllSeasons :exec
UPDATE seasons SET is_active = FALSE WHERE is_active
`

func (q *Queries) DeactivateAllSeasons(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllSeasons)
	return err
}

const getActiveSeason = `-- name: GetActiveSeason :one
SELECT id, name, is_active, created_at FROM seasons WHERE is_active LIMIT 1
`

func (q *Queries) GetActiveSeason(ctx context.Context) (Season, error) {
	row := q.db.QueryRow(ctx, getActiveSeason)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, name, is_active, created_at FROM seasons WHERE id = $1
`

func (q *Queries) GetSeason(ctx context.Context, id int64) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, id)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, name, is_active, created_at FROM seasons ORDER BY is_active DESC, created_at DESC
`

// La activa primero: el frontend la toma de aca cuando una pantalla necesita
// "la temporada en curso" sin preguntar.
func (q *Queries) ListSeasons(ctx context.Context) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveSeason = `-- name: SetActiveSeason :exec
UPDATE seasons SET is_active = (id = $1::bigint)
`

// Una sola temporada en curso: activa la elegida y apaga el resto de una.
func (q *Queries) SetActiveSeason(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setActiveSeason, id)
	return err
}
