// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seasons.sql

package sqlcgen

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, kind, slug, is_demo)
VALUES ($1::text, $2::text, $3::text, $4::boolean)
RETURNING id, name, kind, slug, is_demo, created_at
`

type CreateOrganizationParams struct {
	Name   string `json:"name"`
	Kind   string `json:"kind"`
	Slug   string `json:"slug"`
	IsDemo bool   `json:"is_demo"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Kind,
		arg.Slug,
		arg.IsDemo,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Slug,
		&i.IsDemo,
		&i.CreatedAt,
	)
	return i, err
}

const createSeason = `-- name: CreateSeason :one

INSERT INTO seasons (name, organization_id, is_active)
VALUES ($1::text, $2::bigint, $3::boolean)
RETURNING id, name, is_active, created_at, organization_id
`

type CreateSeasonParams struct {
	Name           string `json:"name"`
	OrganizationID int64  `json:"organization_id"`
	IsActive       bool   `json:"is_active"`
}

// Todas las consultas de temporadas llevan organization_id (C17 §A). Una
// temporada pedida por id que no es de la organizacion no existe: ErrNoRows,
// que el handler traduce a 404 y no a 403 —un 403 confirmaria que el id
// existe en otro lado.
// Nace activa o no segun se pida: crearla inactiva y "restituir" la anterior
// chocaria con el indice seasons_one_active_per_org a mitad del UPDATE.
func (q *Queries) CreateSeason(ctx context.Context, arg CreateSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, createSeason, arg.Name, arg.OrganizationID, arg.IsActive)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const deactivateAllSeasons = `-- name: DeactivateAllSeasons :exec
UPDATE seasons SET is_active = FALSE
WHERE is_active AND organization_id = $1::bigint
`

// Acotado a la organizacion: sin el WHERE, crear una temporada en un grupo
// apagaria la temporada en curso de todos los demas.
func (q *Queries) DeactivateAllSeasons(ctx context.Context, organizationID int64) error {
	_, err := q.db.Exec(ctx, deactivateAllSeasons, organizationID)
	return err
}

const getActiveSeason = `-- name: GetActiveSeason :one
SELECT id, name, is_active, created_at, organization_id FROM seasons
WHERE is_active AND organization_id = $1::bigint
LIMIT 1
`

func (q *Queries) GetActiveSeason(ctx context.Context, organizationID int64) (Season, error) {
	row := q.db.QueryRow(ctx, getActiveSeason, organizationID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one

SELECT id, name, kind, slug, is_demo, created_at FROM organizations WHERE id = $1::bigint
`

// ============================================================================
// Organizaciones
// ============================================================================
func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Slug,
		&i.IsDemo,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, kind, slug, is_demo, created_at FROM organizations WHERE slug = $1::text
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Slug,
		&i.IsDemo,
		&i.CreatedAt,
	)
	return i, err
}

const getSeason = `-- name: GetSeason :one
SELECT id, name, is_active, created_at, organization_id FROM seasons
WHERE id = $1::bigint AND organization_id = $2::bigint
`

type GetSeasonParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetSeason(ctx context.Context, arg GetSeasonParams) (Season, error) {
	row := q.db.QueryRow(ctx, getSeason, arg.ID, arg.OrganizationID)
	var i Season
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getUserByOrgEmail = `-- name: GetUserByOrgEmail :one
SELECT id, name, email, password_hash, must_change_password, created_at, last_login_at, organization_id FROM users
WHERE organization_id = $1::bigint AND lower(email) = lower($2::text)
`

type GetUserByOrgEmailParams struct {
	OrganizationID int64  `json:"organization_id"`
	Email          string `json:"email"`
}

// La cuenta de una organizacion por email: la sesion de invitado de la demo
// entra con la direccion de la organizacion demo.
func (q *Queries) GetUserByOrgEmail(ctx context.Context, arg GetUserByOrgEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOrgEmail, arg.OrganizationID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
	)
	return i, err
}

const listSeasons = `-- name: ListSeasons :many
SELECT id, name, is_active, created_at, organization_id FROM seasons
WHERE organization_id = $1::bigint
ORDER BY is_active DESC, created_at DESC
`

// La activa primero: el frontend la toma de aca cuando una pantalla necesita
// "la temporada en curso" sin preguntar.
func (q *Queries) ListSeasons(ctx context.Context, organizationID int64) ([]Season, error) {
	rows, err := q.db.Query(ctx, listSeasons, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Season{}
	for rows.Next() {
		var i Season
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActiveSeason = `-- name: SetActiveSeason :exec
UPDATE seasons SET is_active = TRUE
WHERE id = $1::bigint AND organization_id = $2::bigint
`

type SetActiveSeasonParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

// Enciende una. Va siempre despues de DeactivateAllSeasons, en la misma
// transaccion: hacerlo en un solo UPDATE (is_active = (id = $1)) choca con
// el indice parcial seasons_one_active_per_org cuando Postgres procesa la
// nueva antes de apagar la vieja. El indice es el que garantiza que nunca
// haya dos en curso por organizacion.
func (q *Queries) SetActiveSeason(ctx context.Context, arg SetActiveSeasonParams) error {
	_, err := q.db.Exec(ctx, setActiveSeason, arg.ID, arg.OrganizationID)
	return err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM organizations WHERE slug = $1::text)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
