// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, role, must_change_password)
VALUES (
  $1::text,
  $2::text,
  $3::text,
  $4::text,
  $5::boolean
)
RETURNING id, name, email, password_hash, role, must_change_password, created_at, is_active, last_login_at
`

type CreateUserParams struct {
	Name               string `json:"name"`
	Email              string `json:"email"`
	PasswordHash       string `json:"password_hash"`
	Role               string `json:"role"`
	MustChangePassword bool   `json:"must_change_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.MustChangePassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.IsActive,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role, must_change_password, created_at, is_active, last_login_at FROM users WHERE lower(email) = lower($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.IsActive,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, role, must_change_password, created_at, is_active, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.IsActive,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, role, must_change_password, created_at, is_active, last_login_at FROM users ORDER BY role, name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.IsActive,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $1::text,
    must_change_password = $2::boolean
WHERE id = $3::bigint
`

type SetUserPasswordParams struct {
	PasswordHash       string `json:"password_hash"`
	MustChangePassword bool   `json:"must_change_password"`
	ID                 int64  `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.MustChangePassword, arg.ID)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1::bigint
`

// Sella el ingreso: a partir de aca la invitacion deja de estar pendiente.
func (q *Queries) TouchUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name      = $1::text,
    email     = $2::text,
    role      = $3::text,
    is_active = $4::boolean
WHERE id = $5::bigint
RETURNING id, name, email, password_hash, role, must_change_password, created_at, is_active, last_login_at
`

type UpdateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
	IsActive bool   `json:"is_active"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.IsActive,
		&i.LastLoginAt,
	)
	return i, err
}
