// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const copySeasonMembers = `-- name: CopySeasonMembers :exec
INSERT INTO season_members (season_id, user_id, role)
SELECT $1::bigint, m.user_id, m.role
FROM season_members m
JOIN seasons de ON de.id = m.season_id
JOIN seasons a  ON a.id = $1::bigint
WHERE m.season_id = $2::bigint AND m.left_at IS NULL
  AND de.organization_id = $3::bigint
  AND a.organization_id  = $3::bigint
ON CONFLICT (season_id, user_id) DO NOTHING
`

type CopySeasonMembersParams struct {
	ToSeasonID     int64 `json:"to_season_id"`
	FromSeasonID   int64 `json:"from_season_id"`
	OrganizationID int64 `json:"organization_id"`
}

// El equipo de una temporada pasa a la siguiente con su rol. Es el default
// del asistente: vienen todas tildadas y se destilda a las que se fueron.
// Las dos temporadas tienen que ser de la organizacion.
func (q *Queries) CopySeasonMembers(ctx context.Context, arg CopySeasonMembersParams) error {
	_, err := q.db.Exec(ctx, copySeasonMembers, arg.ToSeasonID, arg.FromSeasonID, arg.OrganizationID)
	return err
}

const countAdminsInSeason = `-- name: CountAdminsInSeason :one
SELECT count(*)::bigint FROM season_members m
JOIN seasons s ON s.id = m.season_id
WHERE m.season_id = $1::bigint
  AND s.organization_id = $2::bigint
  AND m.role = 'admin' AND m.left_at IS NULL
`

type CountAdminsInSeasonParams struct {
	SeasonID       int64 `json:"season_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Nunca una temporada sin direccion.
func (q *Queries) CountAdminsInSeason(ctx context.Context, arg CountAdminsInSeasonParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminsInSeason, arg.SeasonID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMembershipsOfUser = `-- name: CountMembershipsOfUser :one

SELECT count(*)::bigint FROM season_members m
JOIN seasons s ON s.id = m.season_id
WHERE m.user_id = $1::bigint
  AND s.organization_id = $2::bigint
`

type CountMembershipsOfUserParams struct {
	UserID         int64 `json:"user_id"`
	OrganizationID int64 `json:"organization_id"`
}

// ============================================================================
// Participacion por temporada (season_members)
// ============================================================================
// season_members no tiene organization_id: cuelga de seasons. Cada consulta
// exige que la temporada sea de la organizacion; una que no lo es no devuelve
// filas (y un INSERT sobre ella no inserta nada).
// Cuantas temporadas lleva.
func (q *Queries) CountMembershipsOfUser(ctx context.Context, arg CountMembershipsOfUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsOfUser, arg.UserID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSellerMembershipsOfUser = `-- name: CountSellerMembershipsOfUser :one
SELECT count(*)::bigint FROM season_members m
JOIN seasons s ON s.id = m.season_id
WHERE m.user_id = $1::bigint
  AND s.organization_id = $2::bigint
  AND m.role IN ('seller', 'admin')
`

type CountSellerMembershipsOfUserParams struct {
	UserID         int64 `json:"user_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Si alguna vez fue corista: es lo que habilita a mirar SUS ventas y SU
// rendicion aunque este año no este en el coro. Quien solo estuvo en la
// puerta no tiene ventas propias que mirar.
func (q *Queries) CountSellerMembershipsOfUser(ctx context.Context, arg CountSellerMembershipsOfUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSellerMembershipsOfUser, arg.UserID, arg.OrganizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// CROSS-TENANT a proposito: es el chequeo del arranque ("¿hay alguien
// cargado?"), antes de que exista organizacion alguna.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, must_change_password, organization_id)
VALUES (
  $1::text,
  $2::text,
  $3::text,
  $4::boolean,
  $5::bigint
)
RETURNING id, name, email, password_hash, must_change_password, created_at, last_login_at, organization_id
`

type CreateUserParams struct {
	Name               string `json:"name"`
	Email              string `json:"email"`
	PasswordHash       string `json:"password_hash"`
	MustChangePassword bool   `json:"must_change_password"`
	OrganizationID     int64  `json:"organization_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.OrganizationID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM season_members m
USING seasons s
WHERE s.id = m.season_id
  AND m.season_id = $1::bigint
  AND m.user_id = $2::bigint
  AND s.organization_id = $3::bigint
`

type DeleteMembershipParams struct {
	SeasonID       int64 `json:"season_id"`
	UserID         int64 `json:"user_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.SeasonID, arg.UserID, arg.OrganizationID)
	return err
}

const formerMembers = `-- name: FormerMembers :many
SELECT
  u.id,
  u.name,
  u.email,
  u.last_login_at,
  ultima.season_name AS last_season_name,
  ultima.role AS last_role,
  (SELECT count(*) FROM tickets t
     JOIN sales sa ON t.sale_id = sa.id
     JOIN functions f ON sa.function_id = f.id
   WHERE sa.seller_id = u.id AND f.season_id = ultima.season_id
     AND NOT sa.is_comp AND t.status <> 'void')::bigint AS last_tickets_sold
FROM users u
JOIN LATERAL (
  SELECT m.season_id, m.role, s.name AS season_name
  FROM season_members m
  JOIN seasons s ON s.id = m.season_id
  WHERE m.user_id = u.id
  ORDER BY m.joined_at DESC
  LIMIT 1
) ultima ON TRUE
WHERE u.organization_id = $1::bigint
  AND NOT EXISTS (
    SELECT 1 FROM season_members m2
    WHERE m2.user_id = u.id AND m2.season_id = $2::bigint
  )
ORDER BY u.name
`

type FormerMembersParams struct {
	OrganizationID int64 `json:"organization_id"`
	SeasonID       int64 `json:"season_id"`
}

type FormerMembersRow struct {
	ID              int64      `json:"id"`
	Name            string     `json:"name"`
	Email           string     `json:"email"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	LastSeasonName  string     `json:"last_season_name"`
	LastRole        string     `json:"last_role"`
	LastTicketsSold int64      `json:"last_tickets_sold"`
}

// Quienes participaron alguna vez pero no de esta temporada. No desaparecen:
// quedan abajo, con su historia, y se las puede reincorporar.
func (q *Queries) FormerMembers(ctx context.Context, arg FormerMembersParams) ([]FormerMembersRow, error) {
	rows, err := q.db.Query(ctx, formerMembers, arg.OrganizationID, arg.SeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormerMembersRow{}
	for rows.Next() {
		var i FormerMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.LastLoginAt,
			&i.LastSeasonName,
			&i.LastRole,
			&i.LastTicketsSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembership = `-- name: GetMembership :one
SELECT m.id, m.season_id, m.user_id, m.role, m.joined_at, m.left_at FROM season_members m
JOIN seasons s ON s.id = m.season_id
WHERE m.season_id = $1::bigint
  AND m.user_id = $2::bigint
  AND s.organization_id = $3::bigint
`

type GetMembershipParams struct {
	SeasonID       int64 `json:"season_id"`
	UserID         int64 `json:"user_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (SeasonMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.SeasonID, arg.UserID, arg.OrganizationID)
	var i SeasonMember
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, name, email, password_hash, must_change_password, created_at, last_login_at, organization_id FROM users
WHERE id = $1::bigint AND organization_id = $2::bigint
`

type GetUserByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

// Todas las consultas de personas llevan organization_id (C17 §A), salvo las
// dos que por definicion no pueden: la del login —todavia no hay sesion, y el
// email es unico por organizacion, no global— y la del arranque.
func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.OrganizationID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
	)
	return i, err
}

const getUserWithMembership = `-- name: GetUserWithMembership :one

SELECT
  u.id, u.name, u.email, u.password_hash, u.must_change_password, u.created_at, u.last_login_at, u.organization_id,
  -- Con left_at el rol se apaga: dejo el coro a mitad de temporada, no vende
  -- mas. Sus ventas y su deuda siguen contando, y su historial lo sigue
  -- viendo (RequireHistory).
  COALESCE(CASE WHEN m.left_at IS NULL THEN m.role END, fallback.role, '')::text AS season_role,
  (m.id IS NOT NULL AND m.left_at IS NULL) AS participates,
  m.left_at,
  o.kind AS organization_kind,
  o.name AS organization_name,
  o.is_demo AS organization_is_demo
FROM users u
JOIN organizations o ON o.id = u.organization_id
LEFT JOIN seasons s ON s.is_active AND s.organization_id = u.organization_id
LEFT JOIN season_members m ON m.user_id = u.id AND m.season_id = s.id
LEFT JOIN LATERAL (
  SELECT m2.role FROM season_members m2
  WHERE m2.user_id = u.id
    AND NOT EXISTS (SELECT 1 FROM seasons WHERE is_active AND organization_id = u.organization_id)
  ORDER BY m2.joined_at DESC LIMIT 1
) fallback ON TRUE
WHERE u.id = $1::bigint
`

type GetUserWithMembershipRow struct {
	ID                 int64       `json:"id"`
	Name               string      `json:"name"`
	Email              string      `json:"email"`
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
	CreatedAt          time.Time   `json:"created_at"`
	LastLoginAt        *time.Time  `json:"last_login_at"`
	OrganizationID     int64       `json:"organization_id"`
	SeasonRole         string      `json:"season_role"`
	Participates       pgtype.Bool `json:"participates"`
	LeftAt             *time.Time  `json:"left_at"`
	OrganizationKind   string      `json:"organization_kind"`
	OrganizationName   string      `json:"organization_name"`
	OrganizationIsDemo bool        `json:"organization_is_demo"`
}

// ============================================================================
// Sesion: el usuario mas su rol en la temporada en curso DE SU organizacion
// ============================================================================
// No lleva organization_id como parametro: es la carga de la sesion, y la
// organizacion sale de la propia fila del usuario. La temporada en curso es la
// de ESA organizacion, no cualquiera que este activa.
//
// `role` viene vacio cuando no participa de esta temporada: ahi solo puede
// mirar su historial. Sin ninguna temporada cargada se cae a la membresia mas
// reciente que tenga: es el arranque, quien instala la app entra antes de que
// exista la primera temporada, y sin esto no podria crearla.
func (q *Queries) GetUserWithMembership(ctx context.Context, id int64) (GetUserWithMembershipRow, error) {
	row := q.db.QueryRow(ctx, getUserWithMembership, id)
	var i GetUserWithMembershipRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
		&i.SeasonRole,
		&i.Participates,
		&i.LeftAt,
		&i.OrganizationKind,
		&i.OrganizationName,
		&i.OrganizationIsDemo,
	)
	return i, err
}

const leaveMembership = `-- name: LeaveMembership :exec
UPDATE season_members m SET left_at = now()
FROM seasons s
WHERE s.id = m.season_id
  AND m.season_id = $1::bigint
  AND m.user_id = $2::bigint
  AND s.organization_id = $3::bigint
`

type LeaveMembershipParams struct {
	SeasonID       int64 `json:"season_id"`
	UserID         int64 `json:"user_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Baja a mitad de temporada: deja de vender, pero sus ventas y su deuda
// siguen contando.
func (q *Queries) LeaveMembership(ctx context.Context, arg LeaveMembershipParams) error {
	_, err := q.db.Exec(ctx, leaveMembership, arg.SeasonID, arg.UserID, arg.OrganizationID)
	return err
}

const listUsersWithMembershipByEmail = `-- name: ListUsersWithMembershipByEmail :many
SELECT
  u.id, u.name, u.email, u.password_hash, u.must_change_password, u.created_at, u.last_login_at, u.organization_id,
  COALESCE(CASE WHEN m.left_at IS NULL THEN m.role END, fallback.role, '')::text AS season_role,
  (m.id IS NOT NULL AND m.left_at IS NULL) AS participates,
  m.left_at,
  o.kind AS organization_kind,
  o.name AS organization_name,
  o.is_demo AS organization_is_demo
FROM users u
JOIN organizations o ON o.id = u.organization_id
LEFT JOIN seasons s ON s.is_active AND s.organization_id = u.organization_id
LEFT JOIN season_members m ON m.user_id = u.id AND m.season_id = s.id
LEFT JOIN LATERAL (
  SELECT m2.role FROM season_members m2
  WHERE m2.user_id = u.id
    AND NOT EXISTS (SELECT 1 FROM seasons WHERE is_active AND organization_id = u.organization_id)
  ORDER BY m2.joined_at DESC LIMIT 1
) fallback ON TRUE
WHERE lower(u.email) = lower($1::text)
ORDER BY u.last_login_at DESC NULLS LAST, u.id
`

type ListUsersWithMembershipByEmailRow struct {
	ID                 int64       `json:"id"`
	Name               string      `json:"name"`
	Email              string      `json:"email"`
	PasswordHash       string      `json:"password_hash"`
	MustChangePassword bool        `json:"must_change_password"`
	CreatedAt          time.Time   `json:"created_at"`
	LastLoginAt        *time.Time  `json:"last_login_at"`
	OrganizationID     int64       `json:"organization_id"`
	SeasonRole         string      `json:"season_role"`
	Participates       pgtype.Bool `json:"participates"`
	LeftAt             *time.Time  `json:"left_at"`
	OrganizationKind   string      `json:"organization_kind"`
	OrganizationName   string      `json:"organization_name"`
	OrganizationIsDemo bool        `json:"organization_is_demo"`
}

// CROSS-TENANT a proposito: es el login, y todavia no hay sesion de la que
// sacar la organizacion. Como el email es unico por organizacion y no
// global, puede haber mas de una fila: el login prueba la contraseña contra
// cada una (ver auth.Login).
func (q *Queries) ListUsersWithMembershipByEmail(ctx context.Context, email string) ([]ListUsersWithMembershipByEmailRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithMembershipByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersWithMembershipByEmailRow{}
	for rows.Next() {
		var i ListUsersWithMembershipByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.OrganizationID,
			&i.SeasonRole,
			&i.Participates,
			&i.LeftAt,
			&i.OrganizationKind,
			&i.OrganizationName,
			&i.OrganizationIsDemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seasonTeamSummary = `-- name: SeasonTeamSummary :one
SELECT
  count(*) FILTER (WHERE m.left_at IS NULL AND u.last_login_at IS NOT NULL)::bigint AS active,
  count(*) FILTER (WHERE m.left_at IS NULL AND u.last_login_at IS NULL)::bigint AS pending,
  count(*) FILTER (WHERE m.left_at IS NOT NULL)::bigint AS left_choir,
  count(*)::bigint AS total
FROM season_members m
JOIN seasons s ON s.id = m.season_id
JOIN users u ON u.id = m.user_id
WHERE m.season_id = $1::bigint
  AND s.organization_id = $2::bigint
`

type SeasonTeamSummaryParams struct {
	SeasonID       int64 `json:"season_id"`
	OrganizationID int64 `json:"organization_id"`
}

type SeasonTeamSummaryRow struct {
	Active    int64 `json:"active"`
	Pending   int64 `json:"pending"`
	LeftChoir int64 `json:"left_choir"`
	Total     int64 `json:"total"`
}

// La franja de arriba de Equipo.
func (q *Queries) SeasonTeamSummary(ctx context.Context, arg SeasonTeamSummaryParams) (SeasonTeamSummaryRow, error) {
	row := q.db.QueryRow(ctx, seasonTeamSummary, arg.SeasonID, arg.OrganizationID)
	var i SeasonTeamSummaryRow
	err := row.Scan(
		&i.Active,
		&i.Pending,
		&i.LeftChoir,
		&i.Total,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $1::text,
    must_change_password = $2::boolean
WHERE id = $3::bigint AND organization_id = $4::bigint
`

type SetUserPasswordParams struct {
	PasswordHash       string `json:"password_hash"`
	MustChangePassword bool   `json:"must_change_password"`
	ID                 int64  `json:"id"`
	OrganizationID     int64  `json:"organization_id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}

const teamForSeason = `-- name: TeamForSeason :many
SELECT
  u.id,
  u.name,
  u.email,
  u.created_at,
  u.last_login_at,
  m.role,
  m.joined_at,
  m.left_at,
  (SELECT count(*) FROM tickets t
     JOIN sales sa ON t.sale_id = sa.id
     JOIN functions f ON sa.function_id = f.id
   WHERE sa.seller_id = u.id AND f.season_id = m.season_id
     AND NOT sa.is_comp AND t.status <> 'void')::bigint AS tickets_sold,
  (SELECT COALESCE(SUM(a.quantity), 0) FROM allocations a
     JOIN functions f ON a.function_id = f.id
   WHERE a.user_id = u.id AND f.season_id = m.season_id)::bigint AS assigned,
  -- Lo cobrado menos lo rendido: lo que todavia tiene en la mano.
  (COALESCE((SELECT SUM(sa.paid_cents) FROM sales sa
     JOIN functions f ON sa.function_id = f.id
   WHERE sa.seller_id = u.id AND f.season_id = m.season_id
     AND NOT sa.is_comp AND sa.voided_at IS NULL), 0)
   - COALESCE((SELECT SUM(st.amount_cents) FROM settlements st
   WHERE st.seller_id = u.id AND st.season_id = m.season_id), 0))::bigint AS balance_cents,
  -- Ingresos que registro en la puerta, en esta temporada: es lo unico que
  -- hace quien esta ahi.
  (SELECT count(*) FROM checkins c
     JOIN tickets t ON t.id = c.ticket_id
     JOIN sales sa ON sa.id = t.sale_id
     JOIN functions f ON f.id = sa.function_id
   WHERE c.user_id = u.id AND f.season_id = m.season_id)::bigint AS checkins
FROM season_members m
JOIN seasons s ON s.id = m.season_id
JOIN users u ON u.id = m.user_id
WHERE m.season_id = $1::bigint
  AND s.organization_id = $2::bigint
ORDER BY m.role, u.name
`

type TeamForSeasonParams struct {
	SeasonID       int64 `json:"season_id"`
	OrganizationID int64 `json:"organization_id"`
}

type TeamForSeasonRow struct {
	ID           int64      `json:"id"`
	Name         string     `json:"name"`
	Email        string     `json:"email"`
	CreatedAt    time.Time  `json:"created_at"`
	LastLoginAt  *time.Time `json:"last_login_at"`
	Role         string     `json:"role"`
	JoinedAt     time.Time  `json:"joined_at"`
	LeftAt       *time.Time `json:"left_at"`
	TicketsSold  int64      `json:"tickets_sold"`
	Assigned     int64      `json:"assigned"`
	BalanceCents int64      `json:"balance_cents"`
	Checkins     int64      `json:"checkins"`
}

// El equipo de una temporada con lo que hace falta para decidir: cuanto
// vendio cada una, cuanto de su cupo uso, cuanto le falta rendir y cuando
// entro por ultima vez. Todo acotado a la temporada, para que el año pasado
// no contamine el de ahora.
func (q *Queries) TeamForSeason(ctx context.Context, arg TeamForSeasonParams) ([]TeamForSeasonRow, error) {
	rows, err := q.db.Query(ctx, teamForSeason, arg.SeasonID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamForSeasonRow{}
	for rows.Next() {
		var i TeamForSeasonRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
			&i.TicketsSold,
			&i.Assigned,
			&i.BalanceCents,
			&i.Checkins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1::bigint
`

// Sella el ingreso: a partir de aca la invitacion deja de estar pendiente.
func (q *Queries) TouchUserLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name  = $1::text,
    email = $2::text
WHERE id = $3::bigint AND organization_id = $4::bigint
RETURNING id, name, email, password_hash, must_change_password, created_at, last_login_at, organization_id
`

type UpdateUserParams struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	ID             int64  `json:"id"`
	OrganizationID int64  `json:"organization_id"`
}

// Identidad nada mas: el rol y la participacion viven en season_members.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.ID,
		arg.OrganizationID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.OrganizationID,
	)
	return i, err
}

const upsertMembership = `-- name: UpsertMembership :one
INSERT INTO season_members (season_id, user_id, role)
SELECT s.id, u.id, $1::text
FROM seasons s, users u
WHERE s.id = $2::bigint
  AND u.id = $3::bigint
  AND s.organization_id = $4::bigint
  AND u.organization_id = $4::bigint
ON CONFLICT (season_id, user_id) DO UPDATE
  SET role = EXCLUDED.role, left_at = NULL
RETURNING id, season_id, user_id, role, joined_at, left_at
`

type UpsertMembershipParams struct {
	Role           string `json:"role"`
	SeasonID       int64  `json:"season_id"`
	UserID         int64  `json:"user_id"`
	OrganizationID int64  `json:"organization_id"`
}

// Solo si la temporada Y la persona son de la organizacion: si no, no inserta
// nada y el caller recibe ErrNoRows.
func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) (SeasonMember, error) {
	row := q.db.QueryRow(ctx, upsertMembership,
		arg.Role,
		arg.SeasonID,
		arg.UserID,
		arg.OrganizationID,
	)
	var i SeasonMember
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}
